### ISSUE TITLE
Implement Fullscreen Overlay on MacOS

### ISSUE THREAD

**Issue by The-Minecraft-Scientist** [lacymorrow/crossover#106]
I was looking around and found [this](https://github.com/electron/electron/pull/11599) issue on the Electron github. Would it be possible to implement overlays for fullscreen apps on MacOS using this feature? I know it was deprecated at one point but there is an issue that states otherwise:
https://github.com/electron/electron/issues/24939

**Comment by lacymorrow** [comment]
I'll give it a shot tonight, thanks @The-Minecraft-Scientist!

**Comment by lacymorrow** [comment]
I had this working a looong time ago, looks like toggling the dock icon in/visible when the app is locked is what broke this feature initially, check it out in the latest release: https://github.com/lacymorrow/crossover/releases/latest

Thanks again @The-Minecraft-Scientist!
