### ISSUE TITLE
Electron error in updating to v2.1.3

### ISSUE THREAD

**Issue by dhabak777** [lacymorrow/crossover#107]
After installing the v2.1.3 update I get this error on launching. Did a clean install as well. Same problem.
![electron error](https://user-images.githubusercontent.com/25349853/136169619-b2e65517-eb24-4a7f-8a00-1d67eb4293df.PNG)

**Comment by OrangGila38** [comment]
Same

**Comment by dhabak777** [comment]
> Same

Try to download v2.1.2 (from the electron website) till this error is fixed. That's what I'm doing. make sure to disable automatic update after u install.

**Comment by lacymorrow** [comment]
I'm actively working on this, will likely deploy 2.1.4 as a revert

**Comment by dhabak777** [comment]
> I'm actively working on this, will likely deploy 2.1.4 as a revert

Take your time, Lacy. Is it possible for you to keep the higher pixel count update from 2.1.3 into 2.1.4? Really want to try it out. Love crossover. There's just nothing quite as good out there.

**Comment by lacymorrow** [comment]
This has been fixed in v2.1.4, please go ahead and update to the latest release: https://github.com/lacymorrow/crossover/releases/latest

cc @dhabak777 @OrangGila38 @marcmascarell
