### ISSUE TITLE
The Colour board trys to open to the left side, but it doesnt show up if its outside the box

### ISSUE THREAD

**Issue by DDaryll** [lacymorrow/crossover#11]
https://prnt.sc/r5xtb7
pressed some rnd keys, now its red, but cant change

**Comment by lacymorrow** [comment]
Oh no! That's a big issue. Can you let me know your operating system? 
I'll try to get a fix up this weekend.

Thanks for flagging!

**Comment by DDaryll** [comment]
Win 10 Pro
Newest updates, nothing special

**Comment by lacymorrow** [comment]
@DDaryll I found an issue with my Appveyor builds causing sporradic issues. I'm building everything locally now, would it be possible for you to test out the 0.2.16 release I've just posted?

https://github.com/lacymorrow/crossover/releases/tag/v0.2.16

Hopefully it will fix things!

**Comment by DDaryll** [comment]
Awesome, its working :)
Good job , Thx :-)

**Comment by lacymorrow** [comment]
Thanks so much for testing @DDaryll!
