### ISSUE TITLE
does this work on valorant?

### ISSUE THREAD

**Issue by sarequl** [lacymorrow/crossover#111]
does this work on valorant?
I didn't find valorant on the list.

**Comment by lacymorrow** [comment]
CrossOver should work on most (if not all) DirectX and OpenGL games, Valorant included.
Most likely it will only work in `Borderless` or `Windowed Fullscreen` modes.

Once you've tried it, make sure to add it to the list please!

**Comment by sarequl** [comment]
I have added it to the list.
please check the pull request.
