### ISSUE TITLE
Support for image overlay

### ISSUE THREAD

**Issue by Blakerunner** [lacymorrow/crossover#112]
I was trying some custom crosshairs to create a much more interesting tanking overlay with the intent of the overlay covering my full screen at 1080p. However I can't seem to get this size of the crosshair to work, it scales down.

I was hoping either to assist in how I could do this, or that if this would be a feature that may be implemented?

**Comment by lacymorrow** [comment]
I'll think about this, technically a fullscreen overlay is outside the scope of this project, but I can see why it might be useful.

There are a slew of issues with how this would work at different resolutions, if I added this feature it would need to be an option separate from the crosshair.

Check back in a couple weeks @Blakezik

**Comment by Blakezik** [comment]
Thanks for the reply @lacymorrow

Yes, I assumed this would be a specific option that allows for a transparent image to replace the crosshair.
The way I see it, it would be up to the user who created the crosshair to ensure it works for whatever resolution they are using.

Big fan. Thanks again.

**Comment by lacymorrow** [comment]
@Blakerunner I posted a pre-release version 3.0 with an option to set the app size and image larger.

The image displayed can be made huge, but not fullscreen. Do you need the ability to display the image at fullscreen?
Check it out and let me know if this works for your issue:
https://github.com/lacymorrow/crossover/releases/tag/v3.0.0-0

**Comment by lacymorrow** [comment]
https://github.com/lacymorrow/crossover/releases/tag/v3.0.0

**Comment by lacymorrow** [comment]
No response, feature is (pretty much) added
