### ISSUE TITLE
crash on windows

### ISSUE THREAD

**Issue by Janaue** [lacymorrow/crossover#117]
hi

I have windows 10 [version 10.0.17763.2300] and I use CrossOver-Portable-2.4.0.exe but when i click to launch i get this 

<img width="407" alt="2021-11-23 11_09_40-Error" src="https://user-images.githubusercontent.com/10972636/143005892-ba45c559-3c07-4626-98b7-50a027ada628.png">

**Comment by MuppetGizmo** [comment]
experiencing the same issue as you

you aint alone on this one

**Comment by lacymorrow** [comment]
I'm uploading what I hope to be a fixed version, would you mind giving it a test to see if it works as expected? https://github.com/lacymorrow/crossover/releases/tag/v2.4.1

**Comment by lacymorrow** [comment]
This is fixed in the latest release: https://github.com/lacymorrow/crossover/releases/latest
