### ISSUE TITLE
Crossover installation doesn't work.

### ISSUE THREAD

**Issue by ThatRedDragon** [lacymorrow/crossover#118]
![image](https://user-images.githubusercontent.com/88072951/143044007-e9c4cde0-3b2a-4c6d-a189-fd2504037c02.png)
I get this error every time I run the exe file.

**Comment by ThatRedDragon** [comment]
No problem, thanks for responding.

**Comment by lacymorrow** [comment]
@ThatRedDragon  I'm uploading what I hope to be a fixed version, should take about 15 minutes but would you mind giving it a test when it's up here? https://github.com/lacymorrow/crossover/releases/tag/v2.4.1

**Comment by ThatRedDragon** [comment]
yeah I'll test it out
I'll let you know if it works

**Comment by lacymorrow** [comment]
It's up now, thanks @ThatRedDragon . If you can, test out the "Tilt" action as well, let me know what you think

**Comment by ThatRedDragon** [comment]
alr Im gonna install the version u put up and tell you if it works

**Comment by ThatRedDragon** [comment]
works very well, thanks for updating

**Comment by lacymorrow** [comment]
@ThatRedDragon Thanks for flagging the error and for helping me test this out, soo much appreciated.
