### ISSUE TITLE
Counter-Strike Global Offensive does not work.

### ISSUE THREAD

**Issue by Vladimir1165** [lacymorrow/crossover#124]
please help does not work in Counter-Strike Global Offensive. There is a dot on the monitor, but not in the game.

**Comment by nipnipj** [comment]
Set the game to borderless window.

**Comment by lacymorrow** [comment]
Thanks @nipnipj 😄 
As he mentioned @Vladimir1165, CrossOver does not handled fullscreen windows in most games. You'll need to run in "Borderless" or "Windowed Fullscreen" modes. I'll leave this open until I get a response, in case there was another issue at play.

**Comment by Vladimir1165** [comment]
Thanks a lot guys! Everything is already working perfectly! Great program!

**Comment by lacymorrow** [comment]
Cheers 🍻
