### ISSUE TITLE
Opacity

### ISSUE THREAD

**Issue by UnregisteredUsername** [lacymorrow/crossover#125]
Whenever I lock the crosshair in place the background turns black at a 100% opacity.
![crossover](https://user-images.githubusercontent.com/77406949/145726760-46f03c57-674c-40a5-97b8-a1b94bcb410f.png)
I'm using Gentoo Linux on the 5.10.76 kernel on DWM.

**Comment by lacymorrow** [comment]
Oh no! This seems to be the same issue shown in #77 and #100 , it's likely an issue with the window manager and Electron/Chromium window transparency, but I don't have the resources to fix OS-specific issues like this. Unfortunately my recommendation is to try another window manager or distro.

**Comment by UnregisteredUsername** [comment]
Oddly enough, I just tried it again at now it works. Maybe I messed with my compositor and forgot about it.
For future reference - I'm using Gentoo with the picom compositor.

**Comment by lacymorrow** [comment]
Thanks for updating!
