### ISSUE TITLE
[Game: Tarkov] CrossOver not working in Tarkov

### ISSUE THREAD

**Issue by SegoItCh** [lacymorrow/crossover#128]
Do you know workaround how they detect crossover? process name? it's just image on top of screen, scums with this function in monitor using this, these are really cheats, what is the problem to provide everyone with the opportunity to use the point for approximate aiming, especially since it does not mean anything(you shoot actually from gun, not in center of screen like in most trash games)

**Comment by lacymorrow** [comment]
I'm really not sure how they detect these things, I'd assume a hash and a process name. If you'd like to test I can build a version with a different name and software ID

**Comment by Chase-V** [comment]
> 

will be cool, lets check?

**Comment by nomis51** [comment]
I think Tarkov uses BattlEye as it's anti-cheat software and this one is going to set suspicious any process running with the topmost flag, which is the case of crossover.

Kinda sad, cause this is not the case with easy-anti-cheat, or at least it allows non-intrusive topmost process to run along the game.

**Comment by Chase-V** [comment]
> I'm really not sure how they detect these things, I'd assume a hash and a process name. If you'd like to test I can build a version with a different name and software ID

Make it, pls, I will test it.

**Comment by lacymorrow** [comment]
Here you go, give it a shot: https://github.com/lacymorrow/crossover/releases/tag/v2.5.2

**Comment by Chase-V** [comment]
> Here you go, give it a shot: https://github.com/lacymorrow/crossover/releases/tag/v2.5.2

![Screenshot 2022-03-11 200058](https://user-images.githubusercontent.com/38985553/157913065-76bb0d80-10e9-4875-9a41-d2c398cf7636.png)
It doen't launch =( 
Neither installed nor portable works. I have uninstalled previously installed versions.

> Here you go, give it a shot: https://github.com/lacymorrow/crossover/releases/tag/v2.5.2

**Comment by lacymorrow** [comment]
Well shoot, I'll fix it later today, sorry about that.

**Comment by lacymorrow** [comment]
Try this one?
https://github.com/lacymorrow/crossover/releases/tag/v2.5.3

**Comment by Chase-V** [comment]
> Try this one? https://github.com/lacymorrow/crossover/releases/tag/v2.5.3

With this build it launches, works for 5-20 minutes, then game detects like "external crosshair", not like "crossover x" in original build.

**Comment by Chase-V** [comment]
But, at least, with this build game allows to connect to the game and play with crosshair for some time

**Comment by JAROD187** [comment]
Good evening, is there any follow-up to the project concerning the banning of the app on the game Tarkov? @lacymorrow

**Comment by lacymorrow** [comment]
Please reach out to their devs, it's my only advice. Sorry 🤷

**Comment by lacymorrow** [comment]
I'm adding some sandbox flags to v, they may allow it then. Check in a week or two.

**Comment by lacymorrow** [comment]
Some folks have reported it is working, I would love to know how you installed the app if this is the case for you.
