### ISSUE TITLE
Keyboard Actions (Hide on keypress) does not support "Alt" key

### ISSUE THREAD

**Issue by BoomsiFTW** [lacymorrow/crossover#129]
The Keyboard Actions (Hide on keypress) does not support "Alt" key.
For example if you want to take a screenshot with alt+print, it will always gets crosshair within the print.

**Comment by lacymorrow** [comment]
Yep, I made an intentional decision when adding the accelerator field to tkambler/electron-preferences to disallow meta-only keyboard shortcuts. 

I'll consider updating this, I opened a ticket for it here: https://github.com/tkambler/electron-preferences/issues/138

**Comment by lacymorrow** [comment]
Done
