### ISSUE TITLE
[OS: Mac] Not supported on Monterey 12.0.1

### ISSUE THREAD

**Issue by ArseBandit** [lacymorrow/crossover#131]
Unfortunately cannot run the app on Monterey as getting error: 

You cannot open the application "CrossOver" because this application is not supported on this Mac.

This is on an Intel 2018 Mac Mini I7.

**Comment by lacymorrow** [comment]
Super weird! Are you using the x64 version? 
I would try both the zip and the dmg files, I'll do more testing as I've just upgraded.

**Comment by lacymorrow** [comment]
Can you try https://github.com/lacymorrow/crossover/releases/tag/v3.0.0? 
It __should __ work
