### ISSUE TITLE
[OS: Mac] Cannot `toggle to show` settings after hiding

### ISSUE THREAD

**Issue by diwqwe** [lacymorrow/crossover#133]
i downloaded crossover arm64.zip and also.dmg when ever I use toggle hide it will hide but when i use toggle hide again it won't show

**Comment by lacymorrow** [comment]
That sounds like a pretty bad bug!

Thanks for flagging @diwqwe , can I get a little more information about the machine? I'm assuming you're on an M1 Mac, can you check in `About this mac` to see which version of macOS you're running?

I don't have an M1 mac to test, but maybe this is something simple I can fix.

**Comment by diwqwe** [comment]
yeah im running it on a m1 mac

**Comment by lacymorrow** [comment]
Sorry, I don't really know what the issue could be, and don't have any Mac silicon to test on.

I just posted debugging instructions in the readme if you are comfortable with the terminal and want to dig further: 
https://github.com/lacymorrow/crossover#debugging

**Comment by lacymorrow** [comment]
@Blakerunner I posted a pre-release version 3.0 with a potential fix, let me know if it works: https://github.com/lacymorrow/crossover/releases/tag/v3.0.0-0

**Comment by lacymorrow** [comment]
Can you try https://github.com/lacymorrow/crossover/releases/tag/v3.0.0?

**Comment by XmutanoX** [comment]
This bug is also happening with me and i'm using windows 10, the hotkey hides the program but doesn't show up again

**Comment by lacymorrow** [comment]
Make sure you're trying the latest release but can you post OS/Version/PC specs and your crossover settings you've changed?

If you reset the app with `CTRL/SHIFT/ALT/R` does the problem persist?

**Comment by XmutanoX** [comment]
sorry for the late response, i've been using the lastest release on a windows 10 x64 lastest build, i've tried using without any configuration change whatsoever and after changing hotkeys to rule out incompatibility on it, also reset the app to default config after and the problem persisted.

I also noticed that if i press the "lock crosshair in place" keybind while it's hidden the crosshair shows up again, but pressing the "show/hide crosshair" keybind while it's hidden still doesn't make it show up

**Comment by KingJoey21** [comment]
I started a new issue before I found this but in 3.1.5 on windows 10 I am also having the bug where I can hide it but it will not return with the same key bind.

I also mentioned I couldn't use this in any full-screen application, I am forced to play in windows borderless, is there a fix to this?

**Comment by lacymorrow** [comment]
@KingJoey21 Thanks for confirming, looks like this isn't a Mac-specific issue

The fullscreen issue is known #64

**Comment by lacymorrow** [comment]
Fixed in https://github.com/lacymorrow/crossover/pull/266
