### ISSUE TITLE
Custom image in crosshair images

### ISSUE THREAD

**Issue by AdnanInayat** [lacymorrow/crossover#134]
Is there any way to add your custom image to the library for crosshair?

**Comment by lacymorrow** [comment]
Yep, you should be able to click and drag any image to the settings or crosshair window.

**Comment by lacymorrow** [comment]
I'm also adding a more obvious button in the settings, you can see it in the latest release, 2.5.5: https://github.com/lacymorrow/crossover/releases/tag/v2.5.5
