### ISSUE TITLE
Not supported on High sierra 10.13.6 says need 11.0 or later

### ISSUE THREAD

**Issue by bossa98765** [lacymorrow/crossover#137]
Is there a way to fix this or am I downloading the wrong one ?
Im on mac btw.

**Comment by lacymorrow** [comment]
I'm not 100%, definitely try both `dmg` and `zip` files to see, and message me here if you still can't get it working.

I'm assuming it's an Electron bug but we'll see

**Comment by lacymorrow** [comment]
Any update?

**Comment by lacymorrow** [comment]
@bossa98765  I posted a pre-release version 3.0 with a fix for this, check it out and let me know how it goes: https://github.com/lacymorrow/crossover/releases/tag/v3.0.0-0

**Comment by lacymorrow** [comment]
https://github.com/lacymorrow/crossover/releases/tag/v3.0.0

**Comment by bossa98765** [comment]
Yo! so it worked. Thank you so much! I didnt think you would ever respond but you prove me wrong.

**Comment by lacymorrow** [comment]
Excellent! 
Glad it worked, I built this for myself and I improve it to improve my development skills. It's awesome to see other folks using something I built for fun.

Make sure you use the latest release! v3.0.0 had a bunch of bugs.

https://github.com/lacymorrow/crossover/releases/latest

**Comment by lacymorrow** [comment]
_(If you're on Windows, consider leaving a review for [CrossOver on the Windows Store](https://apps.microsoft.com/store/detail/crossover-crosshair-overlay/9MTD5ZLN7NL1?hl=en-us&gl=US))_
