### ISSUE TITLE
Doesn't anchor on middle on mac

### ISSUE THREAD

**Issue by Zewwo-Boi** [lacymorrow/crossover#14]
When I click the 4 dots thingy, it goes under the middle of my screen

**Comment by lacymorrow** [comment]
Thanks for the report @Zewwo-Boi! I'll see if I can dig into this sometime this week. Cheers!

**Comment by Zewwo-Boi** [comment]
@lacymorrow Thanks!

**Comment by lacymorrow** [comment]
@Zewwo-Boi I've added quite a few new crosshairs in the most recent verision and will be adding custom crosshairs next, tracking here: https://github.com/lacymorrow/crossover/issues/15

Custom keybond tracking here: https://github.com/lacymorrow/crossover/issues/20

**Comment by Zewwo-Boi** [comment]
@lacymorrow Thanks

**Comment by lacymorrow** [comment]
Centering works differently on different systems apparently but we're trying to account for cross-os. Different games have different "Centers" so it may be off by a bit from your application.
