### ISSUE TITLE
有没有全屏下使用crossover的教程

### ISSUE THREAD

**Issue by cznb666** [lacymorrow/crossover#142]
ahk导入脚本不会，请问有没有教程，谢谢了

**Comment by lacymorrow** [comment]
>Is there a tutorial for using crossover in full screen?
>ahk import script will not, is there any tutorial, thank you

Unfortunately this is a problem with "electron" not crossover.
I recommend windowed fullscreen mode

**Comment by lacymorrow** [comment]
Duplicate of #106
