### ISSUE TITLE
Error: EPERM: operation not permitted

### ISSUE THREAD

**Issue by Nikolai-RR** [lacymorrow/crossover#145]
```
Error: EPERM: operation not permitted, rename 'C:\Users\jramos\AppData\Roaming\CrossOver\preferences.json.2450380334' -> 'C:\Users\jramos\AppData\Roaming\CrossOver\preferences.json'
```

---

CrossOver 2.7.4
Electron 12.2.3
win32 10.0.19044
Locale: en-US

**Comment by dblack850** [comment]
Same issue here.

**Comment by lacymorrow** [comment]
Thanks for reporting, I've pulled that version from the auto-updates. I recommend rolling back to the last working version, 2.5.5: https://github.com/lacymorrow/crossover/releases/latest
