### ISSUE TITLE
-possible or not- Custom crosshair images

### ISSUE THREAD

**Issue by testerfr810** [lacymorrow/crossover#15]
i want if is possible to add personalised dot ?
&
is is possible modify the shortcut ?
&
if is always possible to change 1 or other dot with just a shortcut ?

is lot of question i say.

ty

**Comment by mikerogne** [comment]
I'd like to add a personalized dot too. Or at least make the center dot bigger.

**Comment by lacymorrow** [comment]
@testerfr810 It's definitely possible for me to add these features in the next version. We can add a way to customize the keyboard shortcut, how would you want to be able to personalize the dot?

>if is always possible to change 1 or other dot with just a shortcut ?
Do you mean like a keyboard shortcut to a set of settings? (kind of like a profile chooser?)


@mikerogne I'm hearing you, you want to be able to change the size of the dot (independently of the crosshair). Tracking with #16.

**Comment by lacymorrow** [comment]
I've added a new crosshair chooser that has enabled me to add more crosshairs, adding a custom image will be next.
