### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by Eccomi21** [lacymorrow/crossover#156]
Distro: Arch
Shell: zsh
Has been made executable with `chmod +x CrossOver-3.0.0-i686.pacman`
Error zsh: 
```
eccomi@EDVA /home/eccomi $ ./Desktop/CrossOver-3.0.0-i686.pacman
zsh: exec format error: ./Desktop/CrossOver-3.0.0-i686.pacman
```
File Permissions:
```
eccomi@EDVA /home/eccomi $ stat ./Desktop/CrossOver-3.0.0-i686.pacman
  File: ./Desktop/CrossOver-3.0.0-i686.pacman
  Size: 74764688        Blocks: 146040     IO Block: 4096   regular file
Device: 259,1   Inode: 19796567    Links: 1
Access: (0755/-rwxr-xr-x)  Uid: ( 1000/  eccomi)   Gid: (  998/   wheel)
Access: 2022-04-12 16:43:35.799053191 +0200
Modify: 2022-04-12 16:43:34.989054047 +0200
Change: 2022-04-12 16:43:34.989054047 +0200
 Birth: 2022-04-12 16:43:34.935720770 +0200
```
What am i missing?

**Comment by lacymorrow** [comment]
Unfortunately I can't really offer linux support as I only really test on a few different distros. This seems like it may be a system problem, but just to be sure you could try to see if an older version like https://github.com/lacymorrow/crossover/releases/tag/v2.4.1 works.

I updated some packages and changed my build process around then, so it could have changed something.

**Comment by Eccomi21** [comment]
Same Error, am very sad now. I switched from Windows to linux a few days ago and was like "THIS is the xhair overlay I shall use" but apparently I shall not, at least for now.

**Comment by lacymorrow** [comment]
@Eccomi21 Have you tried some of the other package formats? This app works in most distros I have tested on.

**Comment by Eccomi21** [comment]
@lacymorrow I did now, none of them work for me unfortunately. I was thinking about grabbing the windows version and trying to run it trough wine, which is bass ackwards but might work.

**Comment by Eccomi21** [comment]
Can confirm running the windows portable version trough wine works. It's not ideal, but it works. You could add that as a workaround in the readme if others encounter this problem too.

**Comment by lacymorrow** [comment]
This doesn't sound like a great outcome, I'm going to keep this open as it should work. 

Have you installed other `pacman` packages without issues?

**Comment by lacymorrow** [comment]
@Eccomi21 What CPU does your computer have? It's likely an error due to invalid architecture.

Reading this: https://toolspond.com/handle-exec-format-error/

**Comment by Eccomi21** [comment]
> @Eccomi21 What CPU does your computer have? It's likely an error due to invalid architecture.
> 
> Reading this: https://toolspond.com/handle-exec-format-error/

An Intel i7 8700K, if it really was down to the CPU I'd assume I should've had problems under windows as well But it ran flawlessly there just one week prior. 

I'm probably just going to try the x86_64.AppImage next. I'm sorry I can't help you out, with the Sourcecode available I feel like I should be able to figure out what's wrong myself. But my coding experience is very limited.

**Comment by Eccomi21** [comment]
@lacymorrow I'm a huge fkin Idiot. My smoothbrain went for everything that had .pacman at the end disregarding the actual architecture of the appimage provided. the x86_64.Appimage works flawlessly. Issue closed. Sorry for wasting your time.

**Comment by lacymorrow** [comment]
Not a problem! 
I'm just glad you got it working
