### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mescalito** [lacymorrow/crossover#160]
---
	
	Error: net::ERR_NETWORK_CHANGED:
	Error: net::ERR_NETWORK_CHANGED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6536)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)

	---

	CrossOver 3.0.0
Electron 11.5.0
win32 10.0.19042
Locale: en-US

**Comment by lacymorrow** [comment]
Thanks so much for flagging! This is fixed in the latest version: [lacymorrow/crossover/releases/latest](https://github.com/lacymorrow/crossover/releases/latest)
