### ISSUE TITLE
Use IOHOOK mousedown event in fullscreen?

### ISSUE THREAD

**Issue by yoganlava** [lacymorrow/crossover#184]
Made ADS crosshair resizing for #169 in my [fork](https://github.com/yoganlava/crossover). Doesn't seem to work in csgo when using the AHK script to enable it in fullscreen. Any way to do it? Haven't looked at the code too much indepth yet as this was more of a 2 minute addition. `mousemove` seems to work, however, when in fullscreen as follow mouse works for crosshair.

**Comment by yoganlava** [comment]
Does work windowed though, so thats fine. Haven't tested other games but should work for both windowed and fullscreen windows/borderless

**Comment by yoganlava** [comment]
Seems to be more of a question for https://github.com/wilix-team/iohook

**Comment by lacymorrow** [comment]
That's really odd that the `mousemove` function works but not the `mousedown`, I would assume there's some issue with DirectX taking over that specific mouse feature, but go ahead and post in [wilix-team/iohook](https://github.com/wilix-team/iohook) to see if someone has more insight.

To be honest this project has grown quite a bit to still not support fullscreen, but at the same time I believe not using a native hook to inject the app into fullscreen games also prevents it from being blacklisted/bannable.

**Comment by lacymorrow** [comment]
Stale

**Comment by lacymorrow** [comment]
PR that feature for #169 @yoganlava !
