### ISSUE TITLE
ESC key doesnt work

### ISSUE THREAD

**Issue by vozretic** [lacymorrow/crossover#19]
Since 0.3.1 escape key doesnt work while crossover is running.

**Comment by lacymorrow** [comment]
DANG, I'm so sorry @vozretic I'm pushing up version 0.3.2 in the next 30 minutes and should fix this issue.

**Comment by lacymorrow** [comment]
@vozretic I've pushed version 0.3.1 which fixes this issue and a few other nice-to-haves. If you have the time please give it a whirl and let me know if there are any issues. 

Feel free to request features as well!

**Comment by vozretic** [comment]
it works as intended now, great job 👍
