### ISSUE TITLE
Ability to star/favorite crosshairs and show them separately, mock-up inside

### ISSUE THREAD

**Issue by rknDA1337** [lacymorrow/crossover#191]
_**enhancement/suggestion**_

_& my continued thanks for this very useful application **xoxo**_

I did a quick mock-up, it's pretty straight-forward, the star is meant to be a toggle-icon - it's shown only when hovering a crosshair _(but always shown on ALL already favorited crosshairs, not just in the "Favorite" section! Important for UX)_ 

![crossover-favs-mockup](https://user-images.githubusercontent.com/6824358/171799278-9ee5458a-2757-4cc9-9ce8-5677a7769d0f.png)

**Comment by lacymorrow** [comment]
I love this idea, it'll be a few weeks before I can add it but it would be pretty simple if you're interested in making a PR yourself. Definitely adding for consideration.

**Comment by lacymorrow** [comment]
Duplicate #110
