### ISSUE TITLE
Does not work on windows.

### ISSUE THREAD

**Issue by Electrognome** [lacymorrow/crossover#193]
Does not work on windows, no matter if it's portable or not. 
First it launched fine. I adjusted hotkeys to my liking, then tried them out and not a single one works, (default hotkeys worked with no issues).
I tried to reset everything to default settings, reset button just freezes the whole thing without resetting anything. Closed it trough task manager, launched it again, my mouse cursor is now disabled for some reason, hotkeys still does not work. Closed it trough task manager again, now when running the software it just runs itself in the background without actually working or letting me access the settings.

**Comment by lacymorrow** [comment]
Which version of windows, and which version of Crossover?

**Comment by lacymorrow** [comment]
No response, I personally use Crossover on windows. stale.
