### ISSUE TITLE
Heroes and generals bug

### ISSUE THREAD

**Issue by ClumsyBuddy** [lacymorrow/crossover#194]
Cross hair works great in other games but for some reason it does not show on top of the window in heroes and generals in window mode (not fullscreen window, actual windowed mode). I have to run the AHK script to get it to show ontop and on top of that I have to click the button everytime I click out of the window and back in.
System: Windows 10
Screen Resolution: 2560x1440
Application: Heroes and Generals.
If you need a gif showing the problem or anything else just let me know!
Thanks!

**Comment by lacymorrow** [comment]
See #64 , CrossOver does not work in most games in `Fullscreen` Mode.

A gif would be great though, also if you're using a version besides the latest let me know which

**Comment by ClumsyBuddy** [comment]
I am sorry I can understand how what I said can be misinterpreted. I put heroes and generals in windowed mode. Not bordless windowed mode. Just windowed mode and the crosshair still doesn't show on top unless I use the AHK script. I will make a gif tomorrow demonstrating what I mean.

**Comment by lacymorrow** [comment]
Deplicate: #64
