### ISSUE TITLE
Reset all settings issue

### ISSUE THREAD

**Issue by colazzz2o7** [lacymorrow/crossover#195]
Hello , ive been using the crossover for a little while at this point , its my go to crosshair and i really enjoy it , there is 1 big issue though , every 10 - 15 minutes i accidentally click the "lock crosshair in place " or other features and it ends up popping up the crosshair and getting me killed as i cant move , ive tried to add a different bind to it but then i accidentally click the reset all settings which ends up being far worse because then i have to take a good minute to fix my settings , ive tried to bind the reset all settings to something else but couldnt find a place for that , is there any way you can add this to the next version ?
Thanks a lot cya

**Comment by lacymorrow** [comment]
This is a huge issue, so when I have some time I'll try to take a more in-depth look.

I already have built the way to rebind the `reset`, but I'm worried about people re-binding the `reset` action and then get into a situation where they aren't able to get back to a stable state.

**Comment by lacymorrow** [comment]
Fixed in #265
