### ISSUE TITLE
Allow toggle vs hold settings

### ISSUE THREAD

**Issue by tomvanschaijk** [lacymorrow/crossover#196]
The program allows you to toggle the crosshair on/off when pressing a button, or to hide when HOLDING right mouse. It's, however, not possible to toggle the crosshair on/off with the right mouse button. I'm using the program with Escape From Tarkov (which DOES work, contrary to what some users apparently reported), and use right mouse toggle to go in ADS or out. Being able to hide the overlay when rightclicking once to enter ADS and having it pop up again when rightclicking again, would be perfect. Now, I'm just stick with the overlay on at all times whether I ADS or not, unless I bind the hide to a button, or hold rightclick.

**Comment by lacymorrow** [comment]
Appreciate the feature request, I'll do it when I can find some time

**Comment by lacymorrow** [comment]
Added into the upcoming version

**Comment by dumjaevl** [comment]
When is the upcoming version? :D
