### ISSUE TITLE
Autocenter option

### ISSUE THREAD

**Issue by marcmascarell** [lacymorrow/crossover#2]
If you move the crosshair u fucked it up. There should be an option to center it.

Another cool option would be to save different options for example:

- Medal Of Honor (x: 100, y: 200, color: red, type: cross, ...)

**Comment by lacymorrow** [comment]
Great ideas! I'll add an option to center the crosshair.

Game-specific options would be very cool, but I'm not sure if that would be within the scope of the project. Maybe I could offer 3 "save profiles" to choose from.

**Comment by marcmascarell** [comment]
Yes, in the end the profiles concept is what I was asking :)

**Comment by lacymorrow** [comment]
Added in (stable) 0.2.8:

> Double-click the drag icon to center the crosshair on the current display.
