### ISSUE TITLE
Custom keybind

### ISSUE THREAD

**Issue by lacymorrow** [lacymorrow/crossover#20]
Allow users to choose an alternative set of keys for toggle/untoggle instead of CTRL+SHIFT+ALT+X

**Comment by ChosenDave** [comment]
Is it added  yet? Doesnt know if it is or not ^^

**Comment by lacymorrow** [comment]
Not yet, I'm working on a better way to change app settings and will include this feature.

**Comment by ChosenDave** [comment]
Thank you for your respond! Can't wait for this, and the crosshair to hide when ADS i've seen from other suggestions!

**Comment by lacymorrow** [comment]
Long story long, I need to add a ton of settings in order to do custom keybinds, and the current settings window is already cluttered so I want to incorporate tkambler/electron-preferences, but there are a few bugs with that project I need to fix before I'll feel comfortable using it.

Unfortunately I won't be able to hide the crosshair on ADS, as I have no way of monitoring the mouse events when it is in-game.

**Comment by adeldueast** [comment]
no.. :( Is it not possible to just disable crosshair on mouse events(right click) regardless of if we are in the game? just a like global hot key event? There are tons of apps or program that detects key/mouse events even if we are in an other app .. Correct me if i make no sens. 

Ty for ur response and consideration !

**Comment by lacymorrow** [comment]
The issue is that this app is built with Electron, so I'm only able to implement what is available to Electron APIs. Electron is only able to listen for keyboard `globalShortcuts`, but has no global hooks for the mouse. This also is a reason CrossOver is not bannable and not flagged by anti-cheat, since there are no external hooks into the OS.

This may be possible with https://github.com/wilix-team/iohook, but my main concern is keeping the app working cross-platform.

**Comment by lacymorrow** [comment]
All that said, I should be done with this feature this week, so you will be able to bind the "hide crosshair" action to any keyboard shortcut and can likely accomplish what you want with a macro.

**Comment by lacymorrow** [comment]
@adeldueast I created #84 to track your feature request.

**Comment by lacymorrow** [comment]
This is an alpha version of the next release and includes this feature, if you would be willing to test and provide any feedback it would be much appreciate:
https://github.com/lacymorrow/crossover/releases/tag/2.0.0-alpha

cc @ChosenDave
