### ISSUE TITLE
Hide/Show Not Working in 3.1.5

### ISSUE THREAD

**Issue by KingJoey21** [lacymorrow/crossover#200]
It will hide but not return when pressing the same key bind. 

Secondly, I can't get this to work in any full-screen game mode, I have to play in windows borderless to use.

**Comment by lacymorrow** [comment]
The first problem is a big issue, and I don't think you're the first to report

The second issue is #64 which is a known issue.

**Comment by GreenMan36** [comment]
I'm having the same issue, doesn't work in-game nor when on the windows Desktop.
Win11 x64 OS build below:
![image](https://user-images.githubusercontent.com/5887406/188699656-6c459b5d-ee0e-4a97-8f9f-18bb95e324d9.png)
![image](https://user-images.githubusercontent.com/5887406/188699876-4ccab1f3-efa1-4837-84a0-d7f4ff501fdc.png)
Using two monitors (1080p/1440p).
Let me know if you need more info.

**Comment by lacymorrow** [comment]
I have yet to test in Windows 11, I'll take a look soon.

**Comment by lacymorrow** [comment]
Fixed in https://github.com/lacymorrow/crossover/pull/266
