### ISSUE TITLE
CrossOver.exe Installs every time it's launched.

### ISSUE THREAD

**Issue by KingJoey21** [lacymorrow/crossover#201]
Not sure if this is what it's supposed to do but I came from the windows store to here trying to fix the show/hide bug. but now every time I launch the crossover.exe it has to reinstall, then I get an error so I attempt to launch it a second time then it reinstalls and works. This happens every time.
I am on windows 10.

**Comment by lacymorrow** [comment]
You're reinstalling the app over and over, once you've installed CrossOver.exe you should have it installed by now
