### ISSUE TITLE
Windows 11 22H2 FPS stability issues

### ISSUE THREAD

**Issue by nomis51** [lacymorrow/crossover#204]
Can't really explain why yet, but I've been experiencing FPS stability issues on Windows 11 22H2 when CrossOver is running vs when it's not.

I've been using the app for months on Windows 10 (multiple versions) with zero issue. Yesterday, I upgraded to Windows 11 (fresh installation, not junk remaining), and it had the 21H2 update. Played the same game I always play with CrossOver running, no issue. Today, Windows got updated to 22H2, the game still run at the usual 80-100 FPS, but the second I open CrossOver (not even active, e.g. Ctrl + Shift + Alt + X), it drops to 80 FPS, not going any higher, constant stutters and big drops to 30 FPS, with constants bouncing between 80 and 30 FPS, barely able to keep 60+ FPS for more then 2 seconds. The second I close CrossOver, while in a match, the game become smoother like it was before. Both Msi afterburner and the in-game fps counter report same results.

I currently have no clue about what's going on with the 22H2 udpate that makes CrossOver lag the game I play (don't even know yet if it's the only game), but I wanted to share the issue and I'll keep testing with other games and see what could be the cause. In case, it's something that could be easily fixed to work smoother with Win 11 22H2.

Also... that's pretty unexpected, but it lags even in the menu, e.g. the login screen. The crosshair is having hard time following the mouse... If I move the mouse in circles in the middle of the screen, GPU clock drops by half, usage drops to 0% and FPS to 1 lol... yeah it's boken 

Current games that has the issue :
- Enlisted

Informations :
- Same hardware as Windows 10
- Intel CPU (so I believe it's not related to the AMD performance issues Win 11 had) (not throttling)
- NVidia GPU (latest drivers) (not throttling)
- Game and CrossOver running on an SSD (800Gb free space)
- 8Gb out of 24Gb RAM used while playing, so plenty left
- Msi Afterburner running (like on Windows 10)
- Only other thing running while testing was Discord
- No other overlay

CrossOver Settings (all default except) :
- Follow mouse cursor
- Hide on RMB down

I notice that when CrossOver is active, my GPU usage bounce from 99% (usually what it's running at for this game) to 30%, which cause the frametime to increase and framerate to be very unstable, but it keeps boost at max clock, and doesn't seem to throttle.

CPU also starts to draw about 25% more power, but he's pretty quiet at ~10% usage, which is normal for it.

Note FPS are a bit lower then usual, I suppose because of OBS running.

Here's a video showing the issue : [Video](https://vimeo.com/733026958) (video quality not the best, but enough to see the issue and read Msi's infos)

Edit : 

Seems like it happens with other games I have (Path of Exile, City Skylines and Stray). But, after a fresh windows restart, it's fine. Maybe, 20-30 mins later, it starts to lag and freeze again. Well, I suppose i'm going back to Win 10, because I've experienced other performance issues (not only in games), so it might just be Windows 11 still being just bad right now, despite many fixes.

**Comment by lacymorrow** [comment]
Thanks so. so much for the detailed write-up, I haven't had a ton of time recently to work on the project but I'll look into this soon.

**Comment by lacymorrow** [comment]
Still haven't figured out Windows 11 issues, some users are having issues even getting the app to run.

**Comment by nomis51** [comment]
Yeah, same here, haven't found any constants or anything for the issues. Win 11 seems to be tricky with a lot of stuff

**Comment by DemanNL** [comment]
Nvidia had low performance issues as well in their Geforce Experience because of the new W11 update. Seems to be something to do with hardware acceleration or Hardware Accelerated GPU Scheduling. Maybe this helps looking in the correct direction.

**Comment by DemanNL** [comment]
@nomis51 can you try disabling hardware acceleration and see if it fixes it?
Crossover Preferences -> System Settings -> Uncheck Enable hardware acceleration

**Comment by nomis51** [comment]
The lag (the time the crosshair takes to actually follow the mouse) is defnitely less noticable with hardware acceleration disabled. But, still getting some atrocious FPS drops, stuttering and freezes when I look around, "not slowly". Wouldn't say it's better in that regard with hardware acceleration off.

**Comment by nomis51** [comment]
It's has been 2 weeks by now that I've tried Windows 11 again, I've tried the same games I had issue with, with and without crossover, with and without Hardware acceleration, with fixed crosshair or "follow mouse" crosshair, and I think it's fine now.  It's doesn't seem like having or not the overlay active, lag the game more or less, so I believe it was indeed a Windows 11 or an nvidia driver (with Win 11) issue, that most likely has been fixed now.

**Comment by lacymorrow** [comment]
Wow, that's quite a relief to here. I've been going crazy trying to figure out some of these tougher cross-platform issues.

I appreciate the update! I'll leave this open for a bit. Though it may be closable.
