### ISSUE TITLE
Does not work with Dayz

### ISSUE THREAD

**Issue by Mannyvenus** [lacymorrow/crossover#206]

**Comment by lacymorrow** [comment]
Can you provide more information about OS, specs, settings?

**Comment by Mannyvenus** [comment]
Pc sepcs? I7 10th gen, 2080 Ti, its nothing to do with the system it’s
simply probably not compatible for that single game,

**Comment by lacymorrow** [comment]
No worries, just trying to check all the boxes. 
Are you running in borderless or windowed mode, or fullscreen?

**Comment by Mannyvenus** [comment]
Fullscreen

**Comment by lacymorrow** [comment]
CrossOver does not work with any apps in Fullscreen: #64

I'll reopen this if it has issues in windowed or borderless modes.
