### ISSUE TITLE
Does not work for Mac M1 Monterey (12.5)

### ISSUE THREAD

**Issue by shittymacuser** [lacymorrow/crossover#207]
Tried just about every version (both the arm64.zip and arm64.dmg). Still comes up with "Damaged and cannot be opened" (image 1). I have already changed my settings so that apps can be downloaded from anywhere (image 2). 

Pls help, want to beam kids on rust
<img width="266" alt="Screen Shot 2022-08-10 at 9 40 27 am" src="https://user-images.githubusercontent.com/110946210/183780060-72fd0894-e1c5-4493-869a-97a18985b777.png">

<img width="666" alt="Screen Shot 2022-08-10 at 9 38 44 am" src="https://user-images.githubusercontent.com/110946210/183779913-90f9aeb3-ff15-4893-b289-446bff28c817.png">
d74e.png">
.

**Comment by Yoyopizzacat** [comment]
I got it to work

Open terminal and type: sudo xattr -r -d com.apple.quarantine /Applications/CrossOver.app
Type in your password and now you can use CrossOver!

**Comment by Yoyopizzacat** [comment]
Change “Applications" to wherever you downloaded CrossOver

**Comment by Pedro-Beirao** [comment]
+1 to get this fixed

**Comment by lacymorrow** [comment]
The fix was posted by @Yoyopizzacat, MacOS quarantines un-notarized apps and therefore the only route is to un-quarantine yourself using the above command.

I'm leaving this open as a reminder for others.

**Comment by Pedro-Beirao** [comment]
We can still run un-notarized apps without this command, we just need to right-click the app and click "open".
But with this app, the problem seems to be different.
![Screenshot 2022-09-14 at 15 18 39](https://user-images.githubusercontent.com/82064173/190180290-4f80b66c-e6bb-45b8-9252-566c274a4dad.jpg)

**Comment by shittymacuser** [comment]
> I got it to work
> 
> Open terminal and type: sudo xattr -r -d com.apple.quarantine /Applications/CrossOver.app Type in your password and now you can use CrossOver!

YOOOOO LETS GO IT WORKED I LOVE YOU <3

**Comment by lacymorrow** [comment]
This is interesting @Pedro-Beirao, I'll look into it further as to why it's saying the code has been modified.
