### ISSUE TITLE
Doesn't work in Killing Floor 1?

### ISSUE THREAD

**Issue by marcostux06** [lacymorrow/crossover#210]
I am testing and it only works in windowed mode but not in full screen, could it be solved? greetings

**Comment by GreenMan36** [comment]
https://github.com/lacymorrow/crossover#what-worksdoesnt-work-compatability

Fullscreen doesn't work in most games, especially exclusive fullscreen. The application doesn't inject but runs on top of the game and so, doesn't work in games that have a proper fullscreen mode.

**Comment by lacymorrow** [comment]
Thanks @GreenMan36 , Due to Electron limitations, CrossOver does not work with apps in fullscreen.

See #64
