### ISSUE TITLE
Snapd version fully opaque when locked

### ISSUE THREAD

**Issue by Flypaste** [lacymorrow/crossover#213]
[here's what it looks like unlocked](https://cdn.discordapp.com/attachments/880035338855260180/1028290462215315527/unknown.png)
[here's locked](https://cdn.discordapp.com/attachments/880035338855260180/1028290507459264585/unknown.png)
[and locked in a game](https://cdn.discordapp.com/attachments/880035338855260180/1028290611142471731/unknown.png)

A couple other issues I'm having but are non-critical:
- The overlay gets hidden if the game is in fullscreen or borderless window, only works when in true windowed mode.
- When I press the hide hotkey, I can't unhide it again afterwards with the hotkey.

I'm on arch linux, amd graphics drivers, with X11 window manager. (the default/normal one, not using wayland)
I'm using the latest snapd version, downloaded today.

**Comment by lacymorrow** [comment]
Thanks for flagging these issues, I'm not sure if that's an Electron version or a Chromium bug. I won't be able to properly diagnose this for a few weeks.

A few things you could try:
- Turning off/on hardware acceleration in the Crossover settings
- Running Crossover with elevated privileges
- `git clone` this repo and `npm i && npm run start`

**Comment by lacymorrow** [comment]
> When I press the hide hotkey, I can't unhide it again afterwards with the hotkey. 
Looks like this is tracked here in #216 , could you try setting a different hotkey and see if the issue persists?

> The overlay gets hidden if the game is in fullscreen or borderless window, only works when in true windowed mode.
This is normal for CrossOver. Electron apps are currently unable to create Windows over fullscreen apps.

**Comment by eusebioleite** [comment]
got this fixed by downloading the rpm package normally, then running with `sudo crossover --no-sandbox`

**Comment by eusebioleite** [comment]
> got this fixed by downloading the rpm package normally, then running with `sudo crossover --no-sandbox`

but now having issues with the monitor refresh rate, my monitor's is 165hz, but when playing apex seems like 60hz

**Comment by lacymorrow** [comment]
Got it, the no-sandbox feature is being adopted as the default

**Comment by lacymorrow** [comment]
Tracking here: https://github.com/lacymorrow/crossover/issues/68
