### ISSUE TITLE
save some different settings for different windows of games

### ISSUE THREAD

**Issue by masterma110** [lacymorrow/crossover#218]
The cross of some games may on the center. But some sames not on the center. So if we use this for different games, we need move the cross. But decide a right place of cross is difficult. So I hope we can have a faction of save the place of the cross which we need. Just two or three may be enough. Thanks.

**Comment by lacymorrow** [comment]
Great idea, thanks for posting. I'll have some time soon to work on new features.

**Comment by lacymorrow** [comment]
Duplicate #219

**Comment by masterma110** [comment]
> 

by the way, do u think that make language file is a good idea? Maybe the job of translation can be done with the language used people.

**Comment by lacymorrow** [comment]
I love the idea... It will be a pretty big refactor to make it happen and I will need translators.

**Comment by lacymorrow** [comment]
Opened https://github.com/lacymorrow/crossover/issues/260 to track translations
