### ISSUE TITLE
cant choose a different crosshair

### ISSUE THREAD

**Issue by mogulftw** [lacymorrow/crossover#22]
Not sure if im doing something wrong but when I left click on a different crosshair, nothing changes

**Comment by lacymorrow** [comment]
Hi @mogulftw, you aren't wrong, I'm actively working on a new version that fixes this issue. Are you experiencing the same problems as the folks here?
https://github.com/lacymorrow/crossover/issues/21

**Comment by lacymorrow** [comment]
We should have a new version in a few hours

**Comment by lacymorrow** [comment]
Could you test this version and see if it fixes the issue? 
https://github.com/lacymorrow/crossover/releases/tag/v0.3.3

**Comment by lacymorrow** [comment]
The latest version fixes this issue. 

Thank you for your report! I wouldn't be able to maintain without feedback like this.
