### ISSUE TITLE
State is not being persisted when application relaunches.

### ISSUE THREAD

**Issue by welcometopwn** [lacymorrow/crossover#223]
Am i missing something or is there no way to start CrossOver without having to press the keybind? Besides that a really great project.

**Comment by lacymorrow** [comment]
Crossover should start in whatever state it was in when it last quit, I leave it running 24/7 and it starts in "locked" or active mode when I reboot my pc. Is this not your experience?

**Comment by welcometopwn** [comment]
No unfortunately not, it always starts with the background. I tried it now with the portable exe but same behavior.

**Comment by lacymorrow** [comment]
I will definitely look into this when I have some time, thanks for flagging!

**Comment by lacymorrow** [comment]
Can you let me know what your operating system and version are? 
Also make sure you are using the latest version of CrossOver.

**Comment by lacymorrow** [comment]
Still looking at thiis

**Comment by lacymorrow** [comment]
I'm about to release a new version, hopefully will fix this
