### ISSUE TITLE
Quit does not work on Linux

### ISSUE THREAD

**Issue by tomodachi94** [lacymorrow/crossover#226]
I'm unable to completely quit CrossOver on Linux without terminating all processes related to CrossOver via `qps` on Linux.

**Comment by tomodachi94** [comment]
I'm running Linux Mint with Cinnamon v5.0.7. CrossOver is v3.1.5.

**Comment by lacymorrow** [comment]
Thanks for your issue, could you clarify what you mean by:
> without terminating all processes related to CrossOver via qps on Linux.

Do you mean crossover gets hidden and you have to manually quit crossover processes, before restarting the app?

**Comment by tomodachi94** [comment]
When I unlock and exit the program through the `x` button (or through Alt+F4), the program closes but it remains in the background. When right-clicking on the tray icon and pressing quit, nothing happens. I have to terminate the processes related to CrossOver to get it to close.

Also, this is a separate issue, but if the processes aren't terminated and I try to click the "show" button, nothing occurs.

**Comment by lacymorrow** [comment]
If you unlock and exit the program through the x button (or through Alt+F4), does the tray icon remain visible?

Thanks for clarifying! I think I understand now.

**Comment by tomodachi94** [comment]
The tray icon remains visible after closing with `x`/Alt-F4.

**Comment by lacymorrow** [comment]
Thanks for reporting

**Comment by lacymorrow** [comment]
fixed in develop, gearing up for a new release
