### ISSUE TITLE
mouse button to hide stopped working

### ISSUE THREAD

**Issue by fbcreepy** [lacymorrow/crossover#227]
this function was working fine before. ive unin/reinstalled. searched through settings. cant find a fix to this. it used to work just fine as i had it on right mouse button to hide crosshair so when i aim down sights its not there. now it doesnt hide it even when the setting is checked for right mouse button.

**Comment by fbcreepy** [comment]
upon further inspection, i have realized its the game "day Z" thatit stopped working with. the game pubg for example works with this function even in full screen. with dayz, the reticle shows up but you cannot use the mouse button toggle off setting.

**Comment by lacymorrow** [comment]
Looks like those games are hijacking the mouse somehow. I don't have good workaround. Maybe bind the mouse button to a key and use that to hide the crosshair?
