### ISSUE TITLE
[BUG?] App does not display unless ran twice

### ISSUE THREAD

**Issue by kernel-dev** [lacymorrow/crossover#228]
Hello there, I'm currently on Windows 10 22H2 (Build No.: 19045.2364), and I've been using CrossOver for the past few months with no issue (latest release, v3.1.5), however, as of recently (like a week ago), I've had issues with it where, if I run the app once, it does not display the overlay it typically should/would. Instead, if I run another instance of the app, it displays the first app instance's overlay, and the second app instance's. Here is a recording of this. 

https://user-images.githubusercontent.com/61620747/210693615-3f2018f9-ef11-450d-a784-3e19f87302f5.mp4

If there is anything else I should try in order to fix it, please do let me know.

EDIT: It seems that the application automatically updated. So I don't know what the previous version was.

**Comment by lacymorrow** [comment]
Oh lord, that is technically "by design", since some users prefer having multiple crosshairs.

**Comment by kernel-dev** [comment]
Is there a way to turn it off? I presume not.

**Comment by lacymorrow** [comment]
I can add a way to turn it off in the next update, but if you are seeing that behavior, it likely means there is a `crossover` process already running. Pressing Control-Alt-Shift-X may open a hidden window, or Control-Alt-Shift-R to reset app settings.

When it happens, open task manager to verify there are multiple  `crossover` processes running.

**Comment by kernel-dev** [comment]
I will do that the next time I run the app, thank you for the quick responses :+1:

**Comment by kernel-dev** [comment]
So, while it does seem to open 2 processes, I can close one of them and the other stays. There are indeed multiple instances of CrossOver running when looking at Task Manager. Now, whenever I exit and open the app (fresh re-open, I suppose is the term here), it works fine. Thank you for the help!
