### ISSUE TITLE
centering is higher than true screen center

### ISSUE THREAD

**Issue by nhopfen** [lacymorrow/crossover#23]
Centering function is constant, yet is exactly 7 vertical fine tune adjustments from true center of screen. Left-Right is perfect. Although some games, such as Paladins have cross hairs that are off by 2-3 pixels I think true center is the most common in games.

 Not much of a problem once it is adjusted, but an annoyance for new users of this awesome software.

(I'm on windows 10)

**Comment by lacymorrow** [comment]
Hi @nhopfen, what are you using to determine the center of your screen?

Unfortunately different games use slightly different offsets for "Center", so it's unlikely that the centering will be absolutely perfect, however I've updated so that it centers as close as possible.

I'm using my monitor's built-in crosshair to gauge center, let me know if you have to make adjustments using the new version 0.3.6, and how much adjustment you have to make to center this version. If other people report similar adjustments, I'll edit where Crossover centers.

**Comment by nhopfen** [comment]
Hello, I double checked by viewing picture of a cross drawn at extreme low resolution to ensure centering, and then viewed this in different image viewers in fullscreen mode. I validated with games and this matched on 13/15 of them. I will verify 0.3.6 tonight and give feedback. Thank you for such a quick reply.
(btw I just discovered that crossout hide your overlay, it is running easy anticheat so that's probably why. Not sure I even need it for that game, with its custom crosshair colors and such, but worth the mention)
________________________________

**Comment by lacymorrow** [comment]
Thanks for digging for me! If it makes sense then I'll change it.

That's odd about Crossout, some games offer a "Windowed Fullscreen" mode that seems to work well

**Comment by nhopfen** [comment]
It is now better but not yet perfect for my case. I still have to lower it by 3 increments for most my games but you have a very good point that true center doesn't really exist.  This guy details it beautifully: https://www.youtube.com/watch?v=mV9GCg5BvEw.

Also being unsure about how this might be affected by hardware or some exotic scaling feature applied by screen, OS, or GPU. This might be the best placement already.
The only thing I can suggest as foolproof to help people would be to add the other keyboard shortcuts under the ctrl-alt-shift x in the gui, because I know I tried adjusting it oldschool at first and was getting pissed off while trying to drag the window into the right spot with my mouse. Only then did I see the shortcuts on github  and feel like an idiot. Especially for people who might eventually get your app through some google drive link on a youtube video or something.

PS. this path has also brought me to stumble upon these which are licensed free for commercial use : https://www.kenney.nl/assets/crosshair-pack

**Comment by lacymorrow** [comment]
Okay, this is good info. I'll do some testing tonight and see where most games land and if 3px down is the right place to be. I think the whole GUI needs to be reworked, we can separate the settings and add more information as well as potentially custom keyboard shortcuts.

The crosshair pack looks super cool, I'll probably attempt to integrate it. I'm also working on being able to use custom images in the app, but will be a couple weeks before it's complete.

Thanks again!
