### ISSUE TITLE
CrossOver doesn't work on i3

### ISSUE THREAD

**Issue by tomodachi94** [lacymorrow/crossover#230]
Bit of a shocker (/sarcasm), but CrossOver has an unusable visual glitch in Linux on the [i3 tiling window manager](https://i3wm.org/). The transparency portion is completely broken.

This bug occurs in unlocked and locked mode; I'm mostly concerned about the latter.

The actual crosshair is visible, but it's on top of a black box.
## Screenshot
![screenshot_20230123_194914](https://user-images.githubusercontent.com/68489118/214208882-cfbd16f2-02ed-4df5-86b0-eec9fbee67f8.png)

**Comment by seroperson** [comment]
It works with composite manager like [picom](https://github.com/yshui/picom)

**Comment by tomodachi94** [comment]
Hmm. So it appears that CrossOver is dependent on a compositor being present. We should probably leave a note about this *somewhere*.

(I found [this blog post](https://dev.to/l04db4l4nc3r/compositors-in-linux-1hhb) to be very helpful.)

**Comment by lacymorrow** [comment]
I'm a Linux novice, is this something:
- I can manually install when the user runs the app
- could I test for it and display a link to it
- Add it to the readme

**Comment by tomodachi94** [comment]
> [...]Manually install when the user runs the app

You *could*, but I (and many others) would consider it somewhat invasive. It's also somewhat out of the scope of CrossOver, and it would add extra weight to the binary.

> [...]Test for it and display a link to it

There are [a](https://stackoverflow.com/questions/33195570/detect-if-compositor-is-running) few [ways](https://unix.stackexchange.com/questions/512204/how-to-determine-which-composite-manager-is-running) to test if one is present. I recommend linking to the README section on Linux graphics; I sent a PR a few weeks ago to make a note of compositors in that section.

> Add it to the readme

Already done, see #252.

**Comment by lacymorrow** [comment]
Thanks, I opened a ticket with I3 about it: https://github.com/lacymorrow/crossover/issues/230

**Comment by mercster** [comment]
Doesn't work in KDE either (which has a very extensive compositor.)  Maybe this is a X11/Wayland thing?
