### ISSUE TITLE
Consider distributing via Flatpak (flathub) too 

### ISSUE THREAD

**Issue by otuva** [lacymorrow/crossover#236]
You can check out details here: 
https://github.com/flathub/flathub/wiki/App-Submission

Great app btw :)

**Comment by lacymorrow** [comment]
Thanks Will check it out

**Comment by otuva** [comment]
@lacymorrow Forgot to mention, if you decide to package it, you might want to change the project name due to shadowing of a codeweavers project

https://docs.flatpak.org/en/latest/conventions.html
https://docs.flatpak.org/en/latest/electron.html

**Comment by lacymorrow** [comment]
tracking: https://github.com/lacymorrow/crossover/issues/225
