### ISSUE TITLE
Manually change X and Y values

### ISSUE THREAD

**Issue by Soham365** [lacymorrow/crossover#237]
Can you add the x and y location feature?? I know the x and y locations because it's very difficult to move the crosshair by hand. Please 
🥺.

**Comment by lacymorrow** [comment]
Sure, sounds reasonable.
So you want to type the numbers of where the crosshair will jump to?

**Comment by Luckz** [comment]
Similarly it would be nice to save these as presets in some way so you don't accidentally lose them when you hit the reset hotkey or click a wrong button in the UI.

**Comment by lacymorrow** [comment]
This feature will be in the next version, hopefully released this week.

The presets feature is something multiple folks have asked for, so it may be coming shortly after
