### ISSUE TITLE
[Linux/Debian] Black window behind crosshair

### ISSUE THREAD

**Issue by dagoogle** [lacymorrow/crossover#24]
While in the menu you can see the black bar behind it
![Screenshot from 2020-06-14 19-08-52](https://user-images.githubusercontent.com/8596803/84611371-82ab7180-ae72-11ea-8d6d-8bd18f74d03e.png)
However once you close the menu it doesn't go away, so there's zero transparency for the crosshair
![Screenshot from 2020-06-14 19-07-16](https://user-images.githubusercontent.com/8596803/84611344-6c9db100-ae72-11ea-8c7f-32b911ef52c4.png)

I'm running Ubuntu 18.04.4 LTS
It looks like from one of the issues you found a fix for this?
Is it possible for that to be added to master?

**Comment by lacymorrow** [comment]
Seems to be related to this issue, I'll try the suggested workaround: https://github.com/electron/electron/issues/15947

**Comment by lacymorrow** [comment]
I added a fix that may or may not work in v0.3.10, i'd appreciate it if you try it out.

**Comment by dagoogle** [comment]
Sadly its still there on v0.3.10, in that electron issue thread they also added a [delay](https://github.com/maximegris/angular-electron/commit/0994e6c0b3aab268c5f8ae6cb54f8ed2f312ec36).
I didn't see that in your commit.

**Comment by expandingv0id** [comment]
Same issue on Manjaro XFCE. (Might look a little transparent, I have transparency set on inactive windows)
![image](https://user-images.githubusercontent.com/69422080/89731589-8578ac00-da48-11ea-9ca2-2347c90e0bcc.png)
![image](https://user-images.githubusercontent.com/69422080/89731604-a93bf200-da48-11ea-82ab-5165078d0605.png)

**Comment by nipnipj** [comment]
I have the same issue in linux mint 20.

**Comment by serban-mihai** [comment]
Same for me on Linux Mint 20 XFCE.
Tried all the solutions with `--enable-transparent-visuals` and `--disable-gpu` also set `transparency: true` and tried to force the CSS of the html element to render alpha but nothing successfully.

**Comment by lacymorrow** [comment]
This is tough  guys, I'm sorry I haven't found a solution yet but when [this bug](https://github.com/electron/electron/issues/20933) is fixed I'll be able to update the electron version which may fix this issue as well. For now I'm out of ideas :(

**Comment by nipnipj** [comment]
I've tested version `0.3.21` on Linux mint 20. I get a black box.
![Screenshot from 2021-01-06 14-39-45](https://user-images.githubusercontent.com/36553373/103812915-3ce01180-502d-11eb-8cda-31b0e001d0a8.png)

**Comment by lacymorrow** [comment]
Thanks for testing! I'll look into this further

**Comment by lacymorrow** [comment]
I've posted a pre-release version that updates Electron, give it a try and see if it fixes your issue: https://github.com/lacymorrow/crossover/releases/tag/v1.0.1-alpha

**Comment by nipnipj** [comment]
Version `1.0.1` didn't work for me. I'm one Linux mint 20.1. Pls, someone else confirm.
![sc](https://user-images.githubusercontent.com/36553373/106010955-00ca2a80-6088-11eb-9c5d-6e6c213cea37.png)

**Comment by lacymorrow** [comment]
@nipnipj thanks for testing! I'm attempting to fix this issue for good, I'll let you know when I have another version to test.

**Comment by lacymorrow** [comment]
@nipnipj Tested v1.0.1 i386.deb on Linux Mint 20.1-xfce and can confirm

**Comment by lacymorrow** [comment]
I believe I have fixed the issue (at least in debian), tested on Mint and Ubuntu. Please try one of the 1.0.2 pre-release versions: https://github.com/lacymorrow/crossover/releases/tag/1.0.2
@nipnipj @serban-mihai @dagoogle @expandingv0id

**Comment by nipnipj** [comment]
Yes, it works! I'm on Linux mint 20.1 cinnamon.
![sc1](https://user-images.githubusercontent.com/36553373/106182544-fc2b7200-616c-11eb-93de-a3c97c983ecc.png)

**Comment by nipnipj** [comment]
I noticed that I cannot move the crosshair with `ctrl+alt+shift+arrows`.

**Comment by lacymorrow** [comment]
Tracking for the remaining bug of being unable to move the app window: https://github.com/lacymorrow/crossover/issues/46

**Comment by lacymorrow** [comment]
@nipnipj There was a bug targeting the wrong window when moving with arrow keys (moves the hidden chooser window instead).

It's fixed in the latest release, give it a shot: https://github.com/lacymorrow/crossover/releases/tag/v1.0.3

**Comment by nipnipj** [comment]
I can confirm on Linux mint 20.1 cinnamon. There is not black box (transparecy work correctly) and crosshair can be moved throught `Ctrl+Alt+Shift+Arrows`!

**Comment by BlaDEjavU** [comment]
Same issue on debian 12 bookworm with xfce4
