### ISSUE TITLE
Follow Mouse Creating Jerky Movements

### ISSUE THREAD

**Issue by PRGilland** [lacymorrow/crossover#240]
When I enable the Follow Mouse action, moving the mouse causes very choppy camera movements, which make it appear that the game has low FPS. It also causes mouse movements to appear significantly more sensitive than it is.

It varies by game, but I've tested it in Half-Life, Half-Life 2, Counter-Strike Global Offensive, the Halo Master Chief Collection, and Deep Rock Galactic. HL1, DRG, and Halo were borderline unplayable.

Also, not sure if its implemented or not, but a suggestion for a feature: game-specific presets for crosshair types and position, that loads up when certain games are running. This would be handy for those who run games in windowed mode.

**Comment by lacymorrow** [comment]
Thanks for testing, will check it out

**Comment by lacymorrow** [comment]
Tracked here: https://github.com/lacymorrow/crossover/issues/115
