### ISSUE TITLE
Need help - The crosshair program studently stopped working/showing on screen

### ISSUE THREAD

**Issue by INeedABetterName2** [lacymorrow/crossover#244]
Been using Crossover for half a year but suddenly not working today, run the file but nothing shows up, no menu, no crosshair no matter what I try
-Checked Task Manager 5 programs named ''crossover'' running as usual 
Attempted solutions
-Restart / Reinstall / Restart my pc
-Rick-clicking and Left-clicking the crossover icon at the bottom right of my Windows bar
-Tried to press all the shortcut keys

**Comment by INeedABetterName2** [comment]
More info just in case if it is needed: 
windows 10 
i5-8500
RTX3060 Ti

**Comment by begin-theadventure** [comment]
I have the same problem on Linux, just a blank color.

**Comment by INeedABetterName2** [comment]
No idea how but today I reboot my pc and reinstalled it and it worked as usual. PC being PC I guess.
