### ISSUE TITLE
fortnite

### ISSUE THREAD

**Issue by ZxverOwner** [lacymorrow/crossover#246]
cursor doesnt show when in fortinaiti :(

**Comment by foolofdestiny** [comment]
✅ | Fortnite | Runs in Windowed Fullscreen mode
https://github.com/lacymorrow/crossover#bugs

the autohotkey fix i think coukd use tweaking i had limited success with it (could be as  simple as  bind an obscure key rather then 99% of peoples jump button :-P) but i havent put in the time to learn autohotkey...

what OS are you running?

custom crosshairs in fortnite is considered a bannable thing....youtuber codelife has a  few videos on the subject

anticheat did flag this program once for me. other then that no issues

**Comment by ZxverOwner** [comment]
I have windows 10 but my pc is trash and i cant use wimdowed or ill lag bcs i have a custom resolution :(

**Comment by foolofdestiny** [comment]
im in the same boat.  

did you try the autohot key thing? im gonna try it again. let you know how it goes

if nothing else works put a sticker or somethign on your screen or like clear tape with a sharpie reticle kind of idea :-)

**Comment by lacymorrow** [comment]
duplicate #62

**Comment by lacymorrow** [comment]
Windowed fullscreen works in fortnite again!

**Comment by foolofdestiny** [comment]
but my fps....so precious...
lol
thank u
