### ISSUE TITLE
custom crosshair

### ISSUE THREAD

**Issue by foolofdestiny** [lacymorrow/crossover#247]
no issues with the custom crosshair feature itself but trying to create one trying to use a custom image i have  (so far unsuccessfully)been able to center the reticle dot in the image i try to use...it seems like average pixels in the provided pack crosshairs alot are aroudn 125x125 pixels...and have been using .png format....
im wondering if you have suggestions or ideas
not using tje .svg settings (maybe the knowledge im missin?)
![misalign](https://user-images.githubusercontent.com/84997890/232051787-55bf3dca-17e3-4a31-9a98-921043934e94.png)

im wondering if it is possible to mimic the ability to shift the position of the crosshair on the screen but for the the inner image? lol improving my microsoft paint skills might be easier =)

**Comment by lacymorrow** [comment]
You need an even number of pixels I believe. I'm using 360x360 for most images.
