### ISSUE TITLE
[OS: Plasma] Workaround for KDE Plasma.

### ISSUE THREAD

**Issue by begin-theadventure** [lacymorrow/crossover#249]
So, despite its many capabilities, KDE's Plasma KWin compositor currently doesn't have the option to keep a window above a full-screen window, making this app generally useless (on Plasma).

Fortunately, I found a workaround, in my case using Lutris.

`Pre-launch script` with a compositor that has this option (edit: from what I tested only mutter has it) and `Post-exit script` that runs the previous compositor back, I use it like this:
`Pre-launch script`: /path/to/x.sh
```
#!/bin/bash
gnome-shell --replace
```

`Post-launch script:` /path/to/x.sh
```
#!/bin/bash
kwin_x11 --replace
plasmashell --replace
```

If you have any questions about commands in scripts, or anything else, don't hesitate to ask.

**Comment by lacymorrow** [comment]
Would you want to create a PR and write this down in the readme?

**Comment by lacymorrow** [comment]
cc @begin-theadventure

**Comment by begin-theadventure** [comment]
> Would you want to create a PR and write this down in the readme?

Yes, in which category should I write it? Bugs?

**Comment by lacymorrow** [comment]
Yes please :)
Thank you so much, I haven't had a good laptop in months so haven't been putting much work in here but should have a new one soon

**Comment by begin-theadventure** [comment]
Alright, I'll write about it and submit a pull request soon.

I saw that you started working on the project again, that's great!
As far as I know, this is the best app in this category, plus it's open source and cross platform.
Thanks for your work.

**Comment by begin-theadventure** [comment]
Merged https://github.com/lacymorrow/crossover/pull/272.
