### ISSUE TITLE
[Feature Request] Option to `Toggle Crosshair Opacity to 0 on Mouse Button`

### ISSUE THREAD

**Issue by xzuyn** [lacymorrow/crossover#250]
So I still have issues with the `Hide Crosshair on Mouse Button` option causing lag spikes (#221). I think the lag spike is caused by windows/amd/freesync/whatever seeing the main window change from the crosshair to the game and back.

I feel like this issue could by bypassed by instead of hiding the crosshair with whatever method is currently being used, you **_toggle the opacity of it 0 instead_**. There's already a slider for setting the opacity, and there's already a toggle for hiding on mouse button, so hopefully you can just sorta combine those. Maybe add a button like `Set Opacity to 0 instead when using "Hide Crosshair on Mouse Button"`.

**Comment by lacymorrow** [comment]
you, my friend, get a gold star. Should be much quicker now. in the develop branch
