### ISSUE TITLE
Can't install "CrossOver cannot be closed"

### ISSUE THREAD

**Issue by DaWegi** [lacymorrow/crossover#253]
I wanna install the Programm, but after about 60% through, i get a popup saying "CrossOver cannot be closed. Please close it manually and click Retry again". I dont know what to do, because i can't close it, i can nly cancel the install.

**Comment by lacymorrow** [comment]
I'llI need more information, what operating system, what app version, etc.

Dows the portable version work?

If you are on Windows or Mac, you may be able to use the portable versions.
