### ISSUE TITLE
[OS: Ubuntu] Rust Stuttering

### ISSUE THREAD

**Issue by Daemonrat** [lacymorrow/crossover#269]
When playing windowed fullscreen Rust on Ubuntu 22.04, the overlay causes significant stuttering in game. Sometimes the game would just freeze up for 10 seconds straight, then I press the shortcut to hide the overlay and it goes back to normal performance. I have a 144hz 1080p monitor on the left, which I use to play, and a 60hz 4k monitor on the right for youtube, discord, terminal, notepad, etc. I'm not sure if the program is having a hard time with the resolution mixing, but everything else runs fine. Or maybe Rust doesn't do well with the overlay, but the steam overlay doesn't cause any issues.

**Comment by lacymorrow** [comment]
Shoot, noted.
You mean to hide the settings overlay, correct?

I'm working on some updates to the internals for v4 that may fix things.

**Comment by Daemonrat** [comment]
I mean pressing ctrl+shift+alt+h (default keybind) to hide the xhair all together would stop the stuttering. Hiding the settings ctrl+shift+alt+x does not make the stuttering any less noticeable.

Used it today and it ran smooth as butter
