### ISSUE TITLE
SD

### ISSUE THREAD

**Issue by laverlay** [lacymorrow/crossover#273]
---
	
	Error: EPERM: operation not permitted, rename 'C:\Users\Windows\AppData\Roaming\CrossOver\preferences.json.4221945883' -> 'C:\Users\Windows\AppData\Roaming\CrossOver\preferences.json':
	Error: EPERM: operation not permitted, rename 'C:\Users\Windows\AppData\Roaming\CrossOver\preferences.json.4221945883' -> 'C:\Users\Windows\AppData\Roaming\CrossOver\preferences.json'

	---

	CrossOver 3.0.0
Electron 11.5.0
win32 10.0.19045
Locale: ru

**Comment by lacymorrow** [comment]
There is a more recent version of the app, but if you have this error you can delete the folder `C:\Users\Windows\AppData\Roaming\CrossOver\` and restart the app.

**Comment by lacymorrow** [comment]
Update CrossOver to the latest version
