### ISSUE TITLE
Please implement a keyboard shortcut to close the app, not just hide it

### ISSUE THREAD

**Issue by warsponge** [lacymorrow/crossover#274]
this would be useful as at the moment i have to unhide the program and then click close, but if i can close it with a keyboard shortcut i can easily trigger it to close at the same time the game im playing closes

**Comment by lacymorrow** [comment]
fixed/added as ctrl-shft-alt-Q

**Comment by warsponge** [comment]
thanks, i havent seen an update since last year tho?

**Comment by lacymorrow** [comment]
Hasn't been one, my build server on TravisCI was shut down and I haven't had much time to work on this but I'll try to get a release out soon with the update
