### ISSUE TITLE
Left over target

### ISSUE THREAD

**Issue by Copn** [lacymorrow/crossover#28]
After putting my computer into sleep mode for the night, it auto-updated windows edge on my computer, and the crosshair appeared. I assumed I could just turn it back off, so I tried uninstalling it and reinstalling, but the original crosshair has stayed in its spot, and now I have two, one of which I can't make go away. I have tried restarting my computer to no avail. Any help would be appreciated.

**Comment by lacymorrow** [comment]
Wow, well this is a new one. Really sorry for any inconvenience this caused.

The easiest way to kill it is to open Task manager (CTRL+SHFT+ESC) and end any instances of CrossOver (you may need to click "advanced"). 

You should also try toggling the lock shortcut (CTRL+SHFT+ALT+X) a few times. If the settings menu comes up you should be able to right-click > Close. 

Let me know if you still have issues.
