### ISSUE TITLE
Hide on ADS not working in Battlebit Remastered

### ISSUE THREAD

**Issue by quiche-swe** [lacymorrow/crossover#281]
Hide on ADS doesn't work when playing Battlebit Remastered. Crosshair shows up but right clicking doesen't make it disappear. 

Right clicking on desktop does make the crosshair disappear however, so functionality works. Just not in BBR. 

Link to screen recording showing the issue: https://streamable.com/ziprx9

**Comment by lacymorrow** [comment]
I would imagine they bind their own global shortcuts that take precedence. Try using a different shortcut, maybe bind something like H to both ADS and hide crosshair, and link to your right click

**Comment by lacymorrow** [comment]
I appreciate the screenshot, sorry I wasn't more help
