### ISSUE TITLE
im on macOS, i cant hide background window(the half-transparent thing) ctrl+alt(option on mac)+shift+x doesnt work

### ISSUE THREAD

**Issue by euxrex** [lacymorrow/crossover#285]
im on macOS, i cant hide background window(the half-transparent thing) ctrl+alt(option on mac)+shift+x doesnt work  i dont think i can put a screenshot because i have nothing to capture for this issue ._.

	---
	undefined

	CrossOver 3.1.5
Electron 11.5.0
darwin 22.6.0
Locale: en-US

**Comment by lacymorrow** [comment]
Definitely try switching the keybind for reset to something else, I've tested both intel and apple silicon macs and they _should_ be working

**Comment by lacymorrow** [comment]
It's likely a conflicting app keybind
