### ISSUE TITLE
CrossOver does not work when game is in fullscreen

### ISSUE THREAD

**Issue by RaBBitRApER** [lacymorrow/crossover#289]
Hello,
I tried CrossOver on the game Hunt: showdown, and it works only if I play borderless. When I set the game on fullscreen, my crosshair disappears. It doesnt close, it just doesn't overlay over the game.
Any solution?

**Comment by lacymorrow** [comment]
Unfortunately not possible with Electron, and as a result CrossOver. See discussion #64
