### ISSUE TITLE
I get this error a lot of times, please fix!

### ISSUE THREAD

**Issue by arielsasson** [lacymorrow/crossover#29]
![image](https://user-images.githubusercontent.com/69323248/89573714-69cf9480-d801-11ea-81e5-0c13a44e1dfa.png)
This error keeps happening. My config is "No crosshair" with both size and opacity at 100% (I just use the little red +). When I start the app and I get this error, crossahir starts already fixed and with another color (grey). Then I do this procedure: click "choose crosshair", get a blank window, task manager and kill the process, maybe 4 or 5 times until it loads with my color and unfixed, and get no error. Then, potentially it works, I open the game and sometimes it's on top and sometimes isn't. So I close the game and start all over again maybe 1-2 times and eventually it works! I also get errors (not as often) when i move the window around. But usually these don't mess with the functionality. Sometimes I also try canging the crosshair design in order to check for errors, don't know if this what fixes it or if it's just random. I use windows 10 and have installed the 30th June build.

**Comment by lacymorrow** [comment]
Oh no! That's no good, I'll see what I can do to get that error fixed.

That doesn't sound like the best user experience! What game are you playing? Maybe it's something I can look into.

**Comment by arielsasson** [comment]
Thanks for such a fast answer! I use this for Rust and it's been working, I just have to be a little patient to get it started. Sometimes it starts right away, I don't know why. I downloaded the v3.12 .exe installer, but have used previously just the standalone version in the previous release. Just for the record, these errors show up BEFORE starting the game. If I get problems AFTER starting the game, this is due the game managing to settle in front of it (probably fixable with a borderless app that im about to try - https://github.com/Codeusa/Borderless-Gaming/releases)
Thanks again for your app! It's very kind of you to keep this working.

**Comment by lacymorrow** [comment]
Sorry for the late reply, the problem lies in a dependency of CrossOver which doesn't give windows enough time to write the file before erroring out (Issue: https://github.com/sindresorhus/electron-store/issues/103).

I'm updating CrossOver with a _potential_ fix, you can probably just use the standalone for testing but please let me know if you still get this error. There's one more fix I can try, but unfortunately I'm not able to reproduce the error myself.
