### ISSUE TITLE
Request Confirm EAC

### ISSUE THREAD

**Issue by deinegithub** [lacymorrow/crossover#293]
Hi,
I'd like to have a confirmation if Easy Anti Cheat detects CrossOver / Electron as cheating, couldn't find Information in other places.
I'm using it in Dead by Daylight, and got a small EAC Pop-Up which disappeared instantly so i couldn't identify the message
Best Regards

**Comment by lacymorrow** [comment]
So far only one game has banned Crossover, and it does not affect your account status. Closing Crossover will allow you to open the game.

Here is the discussion: https://github.com/lacymorrow/crossover/issues/79
