### ISSUE TITLE
Turn off reticle and crosshair seperately

### ISSUE THREAD

**Issue by ElectroBytezLV** [lacymorrow/crossover#295]
I'm not sure why this wasnt implemented by default, but the app has crosshairs AND an inbuilt reticle which you can choose and customize. There is no way to just have the reticle without the whole circle crosshair and whatnot.
Guess the only option is to choose one of the custom crosshairs that's only a dot or a cross (which you cannot customize) or choose a custom SVG image which then you cannot resize.

**Comment by lacymorrow** [comment]
The very last "Crosshair" listed is "No Crosshair", it should allow you to show just the reticle :)

It's not very obvious, that could be improved.
