### ISSUE TITLE
[BUG] Hide crosshair on <Action> doesn't work anymore

### ISSUE THREAD

**Issue by nomis51** [lacymorrow/crossover#301]
**Description**

Settings > Crosshair Actions > Hide Crosshair on ADS

Doesn't work anymore on any of the listed buttons. The alternative that is "Resize crosshair on ADS" (new) does work though. This new feature might conflict with the old one?

I have default settings + those changes : 

- Hide crosshair on ADS = Right mouse-button
- Enable tilt > enable tilting left/right on keypress = true
- Tilt left key = Q
- Tilt right key = E
- Reticle = No reticule
- Crosshair = crossdot simple -> green + fushia (no reticule)

Was working prior to yesterday's update (3.2.0)

**To Reproduce**
- Clean install crossover
- Apply the settings mentionned above
- Hold down or tap right mouse button
- The crosshair never disappear, it's always visible

**Screenshots**

**Versions (please complete the following information):**
 - OS:  Windows 10
 - CrossOver Version 3.2.0

**Comment by lacymorrow** [comment]
Thank you! fixed and will release a new version very shortly
