### ISSUE TITLE
Similar issue to #93 I guess

### ISSUE THREAD

**Issue by Aviviviviveee** [lacymorrow/crossover#303]
I try and download the arm64.dmg of version 3.3.3 and it throws this at me (I use an M1 MacBook Pro 2020):

![Screenshot 2023-11-01 at 16 40 50](https://github.com/lacymorrow/crossover/assets/98211163/ffab2391-841c-4b94-b594-9cd41b7f1d1e)

 - OS: I tried on Ventura before, but I upgraded to Sonoma and it still won't work.
 - CrossOver Version: 3.3.3
 
 I did check out #93, and I tried with 2.1.2-zeta, but it still threw the damaged file message at me.
 Anyways, I hope you have a nice day.

**Comment by lacymorrow** [comment]
Thank you for your report! I'll try to fix it today, I would love if you could help me test it. I'll post here when I create an update.

**Comment by lacymorrow** [comment]
If you are comfortable with the terminal you can also try `xattr -d com.apple.quarantine path/to/crossover.app`

**Comment by Aviviviviveee** [comment]
ill check on this daily to see when a version is out for me to test
i wish you the best of luck

**Comment by lacymorrow** [comment]
Try the latest!

**Comment by Aviviviviveee** [comment]
![Screenshot 2023-11-02 at 21 35 16](https://github.com/lacymorrow/crossover/assets/98211163/f50cfec4-2601-4804-8f07-2f89c9730a86)
sadly, still wont work, ill try and run the terminal command

**Comment by Aviviviviveee** [comment]
![Screenshot 2023-11-02 at 21 41 43](https://github.com/lacymorrow/crossover/assets/98211163/dbd93a14-2eec-4206-b882-6e88a11cb22f)
this didnt happen before
i cant get rid of this grey hitmarker and
![Screenshot 2023-11-02 at 21 42 05](https://github.com/lacymorrow/crossover/assets/98211163/3ab81785-d76e-4c9e-aee7-e2f02a78507a)
 after a few seconds it geets a white dot in the middle
i can only get rid of it when quittting the app (occurs with 3.3.3 and 3.3.4 [super annoying])

**Comment by lacymorrow** [comment]
Still having issues?
