### ISSUE TITLE
[ISSUE] Can we have Crossover runnin on windows startup without the rectangle for editing?

### ISSUE THREAD

**Issue by RaBBitRApER** [lacymorrow/crossover#306]
My Crossover always starts in editing mode (Ctrl + Shift + Alt + X) when i turn on my pc. (see attached immage)
Is there a possibility to have it started in normal mode so I dont have to press the shortcut each time I boot my pc? I cant find anything in the options, but maybe I'm just blind.

**Comment by RaBBitRApER** [comment]
![Screenshot 2023-11-05 112452](https://github.com/lacymorrow/crossover/assets/147000890/b7d3dec5-fda5-440e-8c88-ae175aa58e5c)

**Comment by lacymorrow** [comment]
It's doable, I think the guy from #299  does this.

If you lock crossover (Ctrl + Shift + Alt + X) then exit the app (left/right click on the tray), I think it should start exactly how you left it.
