### ISSUE TITLE
Tutorial On How to Make Repo Into Executable. 

### ISSUE THREAD

**Issue by nixywixy** [lacymorrow/crossover#31]
I was wondering if I could get a tutorial by you on how to properly make the repo into an executable (Video plzzzzzzzzzz). I've been sitting here trying to make this thing work with nodejs and its just not working. **[Failed at the crossover@0.3.12 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.]** . I keep getting this message but a video that can help walk me through how to make the repo a executable would be greatly appreciated and would help a bunch. I've been using your program for months and it works great, but I would just like to make my own changes that I can share with my friends. Also, this is my first repo I've ever tried to edit so don't be too technical xD.

**Comment by lacymorrow** [comment]
Hi @nixywixy and sorry for the delay, the "Development" section of the readme has the basic outline but the important bit is the `npm run build`. This step builds the app into an executable using the [electron-builder](https://www.electron.build/) config from the `package.json`

Let me know if this helps!

**Comment by lacymorrow** [comment]
For anyone interested in developing, this app was created using @sindresorhus [electron-boilerplate](https://github.com/sindresorhus/electron-boilerplate)
