### ISSUE TITLE
[ISSUE] Locking the crosshair does not remove the background

### ISSUE THREAD

**Issue by ollineka** [lacymorrow/crossover#318]
I am on Debian 12 (linux)

This is what it looks like before i lock it:
![image](https://github.com/lacymorrow/crossover/assets/151991728/e53f1c5c-3f65-459f-9962-e43d3f1060d4)

And when i lock it nothing changes, except i cant click on it

Ive read that locking it is supposed to hide the background and the buttons

**Comment by lacymorrow** [comment]
What version of the app?

**Comment by lacymorrow** [comment]
Yes this is indeed a bug, I've run into this before with build issues, I'll try to get you a working build. 

I usually only test on a mac so I don't catch Linux bugs often

**Comment by lacymorrow** [comment]
Try v 3.1.5?

**Comment by TechnoLukas** [comment]
[Ubutu] I faced this issue now too.

**Comment by lacymorrow** [comment]
Good to know, thank you!

**Comment by lacymorrow** [comment]
Dupe #302
