### ISSUE TITLE
Double click to center display doesnt work.... 

### ISSUE THREAD

**Issue by peace20021** [lacymorrow/crossover#32]

**Comment by t3chn1c4l** [comment]
Can confirm this is also happening for me. Feel free to message or request further information. Happy to provide

**Comment by lacymorrow** [comment]
Seems to work in MacOS but not Windows. Haven't tested Linux

**Comment by lacymorrow** [comment]
On Chrome Windows, any element with `-webkit-app-region: drag` eats all click events. See https://github.com/electron/electron/issues/1354.

I've found a workaround and this will be fixed in this week's release
