### ISSUE TITLE
[BUG] black background

### ISSUE THREAD

**Issue by IlIIIlIlll** [lacymorrow/crossover#323]
![2024-01-20-15:28:29-screenshot](https://github.com/lacymorrow/crossover/assets/91288352/870727a7-5b47-465f-98b1-df9d3448324f)

black screen after locking 
![2024-01-20-20:48:25-screenshot](https://github.com/lacymorrow/crossover/assets/91288352/972eb783-47cb-4d33-b477-0f1385174f8b)

arch xfce4 on xorg

**Comment by florish-lacy** [comment]
Thank you!

**Comment by lacymorrow** [comment]
Thank you!

**Comment by lacymorrow** [comment]
Duplicate #302
