### ISSUE TITLE
Keybind to Center Crosshair, but not Reset

### ISSUE THREAD

**Issue by t3chn1c4l** [lacymorrow/crossover#34]
Similar to CTRL-SHIFT-ALT-R, but no reset. This would be handy so you don't have to double-click, but also if the double-click isn't working. The Center and Reset keybind works to center for me, but the double-click does not.

Thank you for this program. It's definitely the most customizable and effective, from what I've found <3

**Comment by lacymorrow** [comment]
I have added the keybind CTRL-SHIFT-ALT-C to center the app if double-click doesn't work.
