### ISSUE TITLE
problem with windows bits or bug

### ISSUE THREAD

**Issue by Floppy97** [lacymorrow/crossover#35]
it said to me 64 bits windows needed

**Comment by lacymorrow** [comment]
Oh no! I didn't realize we would have interest from 32-bit users, I'll post a version for you soon.

Thanks for the report!

**Comment by lacymorrow** [comment]
Hello, I've had a chance to fix my build process, can you try this version: https://github.com/lacymorrow/crossover/releases/download/v0.3.18/CrossOver-0.3.18.exe
