### ISSUE TITLE
[REQUEST] Fortnite NEEDS a Fullscreen version!

### ISSUE THREAD

**Issue by obliviator123** [lacymorrow/crossover#351]
**Is your feature request related to a problem? Please describe.**
I really like the program, especially the hide when pressing a certain key part, however most people who use a custom crosshair are competitive and as such will definitely want to run fullscreen mode since it gives such a massive performance increase.

**Describe the solution you'd like**
Have an inbuilt way to work with fortnite, like how the discord overlay works i guess?

**Comment by lacymorrow** [comment]
I'm with you, I play Fort and lose frames playing in windowed mode. It's the biggest request issue I have with Electron. There are ways, but I haven't found a good method for windows using Electron.

PLEASE let me know any ideas you have, I would love to fix this.

Duplicate #62
