### ISSUE TITLE
spam ik krijg het elkekeer weer

### ISSUE THREAD

**Issue by collinhek** [lacymorrow/crossover#352]
---
	
	Error: EPERM: operation not permitted, rename 'C:\Users\Collin Hekkert\AppData\Roaming\CrossOver\preferences.json.1808862898' -> 'C:\Users\Collin Hekkert\AppData\Roaming\CrossOver\preferences.json':
	Error: EPERM: operation not permitted, rename 'C:\Users\Collin Hekkert\AppData\Roaming\CrossOver\preferences.json.1808862898' -> 'C:\Users\Collin Hekkert\AppData\Roaming\CrossOver\preferences.json'

	---

	CrossOver 3.0.0
Electron 11.5.0
win32 10.0.22631
Locale: nl

**Comment by lacymorrow** [comment]
Delete the file and it should be recreated when you start the app next
