### ISSUE TITLE
[ISSUE] Cannot get cross over to work on Fedora 40 Kde spin

### ISSUE THREAD

**Issue by GuardianLiarus** [lacymorrow/crossover#361]
Hello, i just downloaded crossover on linux, here's my system info:

Fedora 40 (KDE Spin)
Running KDE 6 on wayland
Crossover running as appimage through Gear Lever ( has the --no-sandbox %U args)

Basically here's what i try to do, i open crossover press control alt shift + X and nothing happens other than i can't move the window anymore, it still goes behind all other windows and the white part stays on.

Thanks for any help !

**Comment by GuardianLiarus** [comment]
Sorry i didn't see that it was explicitly said that it didn't work on KDE, my bad

**Comment by lacymorrow** [comment]
No worries!
