### ISSUE TITLE
[BUG] Uh why do I have 2 crosshairs?!

### ISSUE THREAD

**Issue by pneumonoultramicroscopicsilicovolcsis** [lacymorrow/crossover#371]
**One crosshair always there and another is customizable**

**Screenshots**:
![Screen Shot](https://github.com/lacymorrow/crossover/assets/174818234/e7bb94ad-2209-4c8a-b47c-68c5b1ff5032)

**Versions (please complete the following information):**
 - OS: [e.g. Mac]
 - CrossOver Version [e.g. v3.3.4]

**Comment by pneumonoultramicroscopicsilicovolcsis** [comment]
Wait what nvm, it fixed somehow

**Comment by lacymorrow** [comment]
Seems like the app failed to close or crashed
