### ISSUE TITLE
[REQUEST] Allow Using Physically Huge Image Files for Crosshair

### ISSUE THREAD

**Issue by HubsChromeFreeze** [lacymorrow/crossover#400]
The Request:

CrossOver works amazingly well for adding a simple crosshair to mark the center of your screen, but I have found it is unable to support large (by this I mean physical size) images on the screen.

I have created a few crosshairs that are around about 3440x1300 pixels for use in Sea of Thieves.  It's more than just a center dot marker, though -- I have created a stadiametric rangefinder and cannon sight that allows instantly knowing the distance to a target, and in knowing this, allows you to aim the cannon to the specified range to skip guesswork when firing at a target.  If I try to use these, however, Crossover just shrinks them down to be "normal crosshair size", AKA not at all visible or in any way usable for it's intended purpose (as the overlay must fill the majority of the screen).  I have attempted to attach an image to display the monstrosity I have created:

![SDMRangefinder-Prototype](https://github.com/user-attachments/assets/c6df39a4-84f5-428b-bb9d-f7854ff33a2b)

Desired Solution:

Change something to allow CrossOver to optionally allow HUGE crosshair overlays to cover the screen (Screen furniture!) via:
* Allowing CrossOver to render over significantly larger area of the screen, up to and including the ENTIRE screen (make a setting to allow it to save on resources for people not intending to use such massive sights?);

* Several possibilities given the above dependency; possibly do this by allowing the "scale" slider in the options to go well over 100 (at the scales needed, it'd probably need to go into the tens or hundreds of thousands, so it may need some adjustments)
OR
* Disable the nicety of CrossOver scaling down images to normal crosshair sizes, so when trying to upload an image of thousands of pixels by thousands of pixels, it will automatically just be huge (but can be scaled down in case somebody just tries to make their crosshair into a super high resolution image of a cat or something but wants it to be smaller)
OR
* Allow directly changing the size of the crosshair's rendering area (the translucent white box) via dragging around its edges or  by specifying dimensions in the config.

Thank you for your time, and I would greatly appreciate this change as I have spent _far_ too long trying to make this thing and I want to see my nerdiness pay off (unfortunately, I'm not good with computers or I'd fork it myself...)

**Comment by HubsChromeFreeze** [comment]
NEVER MIND -- I'm a certified stupid.  I found the option to change the size, and the rangefinder works PERFECTLY....muahahahahaha.... anyway, now I need to calibrate the gun sight...

Well done!

**Comment by lacymorrow** [comment]
Love it <3

Cheers
