### ISSUE TITLE
Add ability to turn off the crosshair while usign ADS.

### ISSUE THREAD

**Issue by wojciechSlodziak** [lacymorrow/crossover#41]
First of all, this is a great, great app.

Do you think it would be possible to add an option to disable the crosshair when you are holding right mouse button?

This seems to be useful in games like Tarkov, where your middle of the screen is not always where your gun will shoot, especially when aiming down sights.

**Comment by lacymorrow** [comment]
Great suggestion! I'll see if this would be possible

**Comment by lacymorrow** [comment]
I've done some research on this and it is possible, but would require a native addon or the use of iohook, which I'm wary of doing until this issue is resolved: https://github.com/wilix-team/iohook/issues/93.

Don't expect this feature too soon.

**Comment by lacymorrow** [comment]
This requires the app to be actively listening (usually to a mouse click).

It's more intrusive than I think this code should be and there is no clear cross-platform route. Therefore, I'm closing this as wontfix
