### ISSUE TITLE
Refresh Rate

### ISSUE THREAD

**Issue by havvk1** [lacymorrow/crossover#43]
Hello, 

Seems whenever I launch it, it noticeably alters my monitor's refresh rate negatively, when I end the task it returns my refresh rate back to normal. 

Any ideas?

**Comment by lacymorrow** [comment]
Thanks for reporting @havvk1, I'll see if there is anything I can do to improve performance.

**Comment by lacymorrow** [comment]
@havvk1 Can you let me know what operating system you use? Windows maybe?

**Comment by havvk1** [comment]
Windows 10 64b

When i launch the program, its almost as if my 240hz refresh rate on the monitor drops to 40-60hz. It doesn't effect my fps, just the refresh rate. very strange.


Sent from Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by lacymorrow** [comment]
@havvk1 that is very odd, I use the app quite often so I'm not sure what could be happening but I'm trying to reproduce now. If you look at the refresh [rate test testufo.com](https://www.testufo.com/) can you see the slowdown occurring?

**Comment by havvk1** [comment]
Yes, i have ran that when i initially realized the issue.

I could easily tell the difference between them all. Then Launched the program, and they all were reduced to appearing the same. small difference between 30-50.

Sent from Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by lacymorrow** [comment]
@havvk1 I'm sort of stumped, I'm getting a solid 240hz on the same OS with only a blip when Crossover is launched. Im assuming it has to be something to do with your GPU, either targeting the wrong GPU or a bug with Chromium, so I'll attach a version with graphics acceleration disabled.

Do me a favor, this is a [pre-release version](https://github.com/lacymorrow/crossover/releases/tag/v1.0.1-alpha) with a ton of changes under the hood, can you **[try this first](https://github.com/lacymorrow/crossover/releases/download/v1.0.1-alpha/CrossOver-Portable-1.0.1.exe)**? If that still has issues, **[here is a version with GPU explicitly disabled](https://github.com/lacymorrow/crossover/releases/download/v1.0.1-alpha/CrossOver-Portable-1.0.1-NO-GPU.exe)**. Try that too.

**Comment by havvk1** [comment]
Thank you,

I will try this tonight after work.

Stay tuned

Sent from Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by lacymorrow** [comment]
Hello @havvk1, were you able to test the GPU vs nonGPU versions?

**Comment by lacymorrow** [comment]
Closed for inactivity
