### ISSUE TITLE
Cross-platform issues

### ISSUE THREAD

**Issue by lacymorrow** [lacymorrow/crossover#5]
ElementaryOS:

- Unable to drag (`CTRL`+`SHIFT`+Arrows works)
- Unable to hide the settings and rest of the application
- Toggle lock seems to make the crosshair opacity 100%
- Resizing the crosshair a bunch leaves behind artifacts in the settings window:
<img width="122" alt="Screen Shot 2019-10-10 at 11 03 56 AM" src="https://user-images.githubusercontent.com/1311301/66594541-332bdd80-eb4e-11e9-9f20-d7e646dfae92.png">

**Comment by lacymorrow** [comment]
Ubuntu:
- Installs but will not launch

**Comment by lacymorrow** [comment]
Windows:

 - Fullscreen apps take precedence, requires running other apps in windowed-fullscreen mode.

**Comment by lacymorrow** [comment]
Fix for Linux transparency issues: 

```
if (process.platform === 'linux') {
    app.commandLine.appendSwitch('enable-transparent-visuals');
    app.commandLine.appendSwitch('disable-gpu');
}
```

**Comment by lacymorrow** [comment]
Added a test fix for the transparency issues in v0.3.10

**Comment by wolewd** [comment]
i got this bug too,
using arch linux with budgie DE
Kernel 5.4.86-1-lts

**Comment by lacymorrow** [comment]
Likely we will need to wait for another bug to be fixed in electron before this can be fixed. My apologies.

**Comment by lacymorrow** [comment]
I've posted a pre-release version that updates Electron, give it a try and see if it fixes your issue: https://github.com/lacymorrow/crossover/releases/tag/v1.0.1-alpha

**Comment by JoelEllis** [comment]
> I've posted a pre-release version that updates Electron, give it a try and see if it fixes your issue: https://github.com/lacymorrow/crossover/releases/tag/v1.0.1-alpha

This doesn't fix it for me (fedora 33, xorg)

**Comment by lacymorrow** [comment]
@JoelEllis thanks for testing! I'm attempting to fix this issue for good, I'll let you know when I have another version to test.

**Comment by lacymorrow** [comment]
I believe I have fixed the issue (at least in debian), tested on Mint and Ubuntu. Please try one of the 1.0.2 pre-release versions: https://github.com/lacymorrow/crossover/releases/tag/1.0.2
@JoelEllis @wolewd @marcmascarell

**Comment by wolewd** [comment]
hi, i already test it with arch linux 5.4.92-1-lts
the transparency issue is fixed now, but still i cant move or drag the crosshair

**Comment by lacymorrow** [comment]
Excellent, thanks for testing @wolewd

**Comment by JoelEllis** [comment]
Yeah, same for me - transparency is fixed, but dragging/arrow keys isn't.

**Comment by lacymorrow** [comment]
Tracking for the remaining bug of being unable to move the app window: https://github.com/lacymorrow/crossover/issues/46

**Comment by lacymorrow** [comment]
There was a bug targeting the wrong window when moving with arrow keys (moves the hidden chooser window instead).

It's fixed in the latest release, tested in Mint, Fedora, and Ubuntu. Sorry @wolewd, Arch is alien to me 👾
https://github.com/lacymorrow/crossover/releases/tag/v1.0.3

**Comment by JoelEllis** [comment]
Thanks so much :smile: I really appreciate you doing all this.
