### ISSUE TITLE
Close button not hiding

### ISSUE THREAD

**Issue by JoelEllis** [lacymorrow/crossover#51]
crossover 1.0.4, Fedora 33 with xorg
![image](https://user-images.githubusercontent.com/28905212/106364017-ead89600-6323-11eb-9985-2efdc9c50ba1.png)
(Sorry about reporting yet another linux bug :smile: )

**Comment by lacymorrow** [comment]
Thanks for the report @JoelEllis! Fixed in 1.0.5: https://github.com/lacymorrow/crossover/releases/tag/v1.0.5

Let me know if you have any more issues.

I noticed Fedora has conflicting key shortcuts so I'm working on the ability to change CrossOver's keybinds

**Comment by JoelEllis** [comment]
So... It fixes the close button still being there after the window is hidden, but now there's no close button at all! Sorry! :smiley:
![image](https://user-images.githubusercontent.com/28905212/106394871-d5806c00-63f6-11eb-98b8-3283be1c7c95.png)
Also, looking through the shortcuts I can't see any that are conflicting. What ones do you think conflict?

**Comment by lacymorrow** [comment]
Oh no!

**Comment by lacymorrow** [comment]
That's super odd, I'm testing in fedora and seems to be working, I must have messed up when compiling, can you try version 1.0.7: minutes:https://github.com/lacymorrow/crossover/releases/tag/v1.0.7

**Comment by JoelEllis** [comment]
1.0.7 seems to be exactly the same - I'm using the appimage install, if that helps?

**Comment by lacymorrow** [comment]
Very weird, I'll take another look today

**Comment by lacymorrow** [comment]
There absolutely is a problem happening during compilation that is screwing this up

**Comment by JoelEllis** [comment]
I can't see a way to open devtools to look at anything from my end, f12 and ctrl+shift+i seem to be disabled. Any way to enable that in the built version?

**Comment by JoelEllis** [comment]
When built from source it has the fully-functioning close button by the way.

**Comment by lacymorrow** [comment]
I uploaded 1.0.9, give it a shot. The OS check doesn’t seem to be.working
on Linux when packaged, not sure why

**Comment by JoelEllis** [comment]
Hi, sorry about forgetting this for a while.
1.0.9 works!
Thanks again!
