### ISSUE TITLE
centering crosshair on stretched resolutions

### ISSUE THREAD

**Issue by myoung6** [lacymorrow/crossover#57]
double clicking the bulls-eye doesnt correctly center the crosshair

**Comment by lacymorrow** [comment]
@myoung6 Is it too high? How many pixels off?

**Comment by myoung6** [comment]
> @myoung6 Is it too high? How many pixels off?

It's too high. When you use the center function it's centered horizontally but just a little too high vertically. I saw you mention that it may not take into account the taskbar and I think that's roughly the amount it's off by, maybe a little more though. I was playing 1440x1080 and 1680x1080

**Comment by lacymorrow** [comment]
This is fixed upstream and will be fixed in the next release, tracking here: https://github.com/lacymorrow/crossover/issues/53

**Comment by lacymorrow** [comment]
Fixed in the latest release https://github.com/lacymorrow/crossover/releases/tag/latest
