### ISSUE TITLE
How can I add a custom crosshair --- one created by myself.

### ISSUE THREAD

**Issue by nipnipj** [lacymorrow/crossover#59]
Is it possible to do it?
How can I do it?
What are the requirements of the image?

**Comment by lacymorrow** [comment]
Sure! Just click and drag the image to the app while unlocked.

There are no requirements to the image, but it will be scaled to fit into the crosshair size

**Comment by nipnipj** [comment]
by unlocking you mean pressing `ctrl + shift + alt + x`, right? I see a `+` symbol when draging it to corners of the windows, but nothing happens.

![Screenshot from 2021-02-26 14-10-23](https://user-images.githubusercontent.com/36553373/109344378-a239cd00-783c-11eb-9a02-1928027d6309.png)

**Comment by lacymorrow** [comment]
Looks like there's a bug here, it's present in Windows too. I'll admit I don't test much on non-mac platforms unless an issue is raised so let me look into this and get back to you.

**Comment by lacymorrow** [comment]
@nipnipj This should be fixed in the latest release: https://github.com/lacymorrow/crossover/releases/tag/latest

**Comment by nipnipj** [comment]
Linux mint 20.1 cinnamom, here. It works! I can draw images to the app while unlocked. Now I need to create my perfect crossair.
Also I have to mention that the download speed was extremely slow --- this didn't happen before.

**Comment by lacymorrow** [comment]
@nipnipj Thanks so much for letting me know! (I didn't test in linux, just crossed my fingers)

Not sure why the download speed was slower, may be a github issue.
