### ISSUE TITLE
Feature Request: 200% Size (Better resolution)

### ISSUE THREAD

**Issue by dreuseff** [lacymorrow/crossover#60]
On my 4k monitor (and Windows 10 Pro x64), the crosshairs feel really small to me.  Could I get a checkbox (or something) to allow the size to go to 200%?

**Comment by lacymorrow** [comment]
I just got a new monitor myself, I can see what you mean.

I'll try to get this in the next release.

**Comment by lacymorrow** [comment]
I'm bumping the max size by 25% (up to 125px) as a band-aid in the meantime
