### ISSUE TITLE
[Feature] Toggle Between Two Crosshairs

### ISSUE THREAD

**Issue by dreuseff** [lacymorrow/crossover#61]
I would love to be able to switch from a crosshair for dark environments to one for light environments with a hotkey.  This would allow me to use a smaller, more precise crosshair instead of having something that is bold enough to show up in all situations.

**Comment by lacymorrow** [comment]
I'm planning to implement saved presets in #110 , this feature will probably be a keybind for a saved preset.

**Comment by lacymorrow** [comment]
I've added a keybind to switch to the next duplicate crosshair
