### ISSUE TITLE
Performance issues in certain games (Titanfall 2)

### ISSUE THREAD

**Issue by pulsebladebonehead** [lacymorrow/crossover#70]
When I use crossover with Titanfall 2 I get lag spikes. I’ve tried using lower quality settings but it doesn’t change much. I’ve also not noticed any more specific source of lag other than running crossover.

**Comment by lacymorrow** [comment]
Interesting! You're the only other person who has experienced any sort of performance loss.

Any other info that you can provide like OS, system hardware?

It sounds like you may be having issues with GPU acceleration, could you try the "non-GPU" version that I have listed here: https://github.com/lacymorrow/crossover/issues/43

If that fixes the lag spikes then I will know how to fix it. I'm working on a new version with the option to disable GPU acceleration, but it's not ready yet.

**Comment by lacymorrow** [comment]
This is an alpha version of the next release and includes this feature, if you would be willing to test and provide any feedback it would be much appreciate:
https://github.com/lacymorrow/crossover/releases/tag/2.0.0-alpha

cc @pulsebladebonehead
