### ISSUE TITLE
Destiny 2 Fullscreen not working

### ISSUE THREAD

**Issue by adushaj** [lacymorrow/crossover#71]
Your documentation says this works in fullscreen but appears maybe a patch for the game broke that. Using the AHK isn't acceptable as there is noticeable input lag. Any way I can help you look into this? Would LOVE for the app to work in fullscreen Destiny 2

**Comment by lacymorrow** [comment]
What OS are you using, it would be good to start collecting this info. I really don't have an answer for the fullscreen issue, it's a limitation of Electron and the OS, not Crossover.

**Comment by adushaj** [comment]
I’m on Windows 10 Build 19041.985

Nvidia Driver version 466.27

Aleks

**Comment by lacymorrow** [comment]
Okay, I'll update the readme.
