### ISSUE TITLE
How do u even start this thing?

### ISSUE THREAD

**Issue by gdfgdfgdfgfdhdhgfh** [lacymorrow/crossover#73]
How do u start this thing??
Where is exe?
Its just bunch of random shit, just make exexexexexeexeexececexee

**Comment by lacymorrow** [comment]
Ha did you happen to see the large "Download for Windows" link? Or the multiple `exe` files on the [releases page](https://github.com/lacymorrow/crossover/releases/latest)?

Here you go, bud:
https://github.com/lacymorrow/crossover/releases/latest/download/CrossOver.exe
