### ISSUE TITLE
Worked in a game but now its not

### ISSUE THREAD

**Issue by Issue3** [lacymorrow/crossover#74]
Valorant, I was playing valorant, and once I opened it again it stopped working for it but if I sign into another account it works
anything you know bout this?

**Comment by nipnipj** [comment]
I do not think there is anything related to account switching. Just play your games in window/window borderless mode.

**Comment by Issue3** [comment]
> I do not think there is anything related to account switching. Just play your games in window/window borderless mode.

no it was working in full screen

**Comment by lacymorrow** [comment]
I cannot guarantee that it will work in Fullscreen mode unfortunately.
