### ISSUE TITLE
Not opening

### ISSUE THREAD

**Issue by couldntcarelesskys** [lacymorrow/crossover#75]
Whenever I try to open it it doesn't do anything, even when I tried uninstalling and installing again.

**Comment by lacymorrow** [comment]
@couldntcarelesskys Can you provide more information about what operating system you're using and which version of the app you are trying to run?

**Comment by couldntcarelesskys** [comment]
I'm using windows 10 and I've used 0.2.14 and even the most recent version but still doesn't work.

**Comment by lacymorrow** [comment]
I've just posted version 1.3.1, could you try uninstalling and using the latest [installer](https://github.com/lacymorrow/crossover/releases/download/v1.3.1/CrossOver.exe) or [portable](https://github.com/lacymorrow/crossover/releases/download/v1.3.1/CrossOver-Portable-1.3.1.exe)?

**Comment by couldntcarelesskys** [comment]
Hey. sorry didn't see your reply. But I've just tried it and it's still not working

**Comment by couldntcarelesskys** [comment]
I'll try the portable now

**Comment by couldntcarelesskys** [comment]
It's working. Thanks

**Comment by couldntcarelesskys** [comment]
> I've just posted version 1.3.1, could you try uninstalling and using the latest [installer](https://github.com/lacymorrow/crossover/releases/download/v1.3.1/CrossOver.exe) or [portable](https://github.com/lacymorrow/crossover/releases/download/v1.3.1/CrossOver-Portable-1.3.1.exe)?

Do you have any tips for it to work in csgo fullscreen?

**Comment by lacymorrow** [comment]
Unfortunately not running in fullscreen is a limitation of Electron. Until they create support for it, I won't be able to add it to CrossOver.

**Comment by couldntcarelesskys** [comment]
> Unfortunately not running in fullscreen is a limitation of Electron. Until they create support for it, I won't be able to add it to CrossOver.

Ok it's fine.
