### ISSUE TITLE
Weird Issue with CSGO on Manjaro

### ISSUE THREAD

**Issue by bunkbail** [lacymorrow/crossover#77]
I haven't tried crossover on Windows, but it has pretty weird issue with CSGO on Manjaro KDE. Crossover doesn't work in either fullscreen and windowed fullscreen modes but it works in windowed mode but after toggling Ctrl+Alt+Shift+X it has black borders around the crosshair. 

![Screenshot_20210627_001132](https://user-images.githubusercontent.com/8214150/123506932-5a676d00-d699-11eb-941f-a9b0237db3cc.png)

**Comment by lacymorrow** [comment]
I haven't tested in Manjaro, so I'll try to make some time to do that.

**Comment by bunkbail** [comment]
I tried on Pop OS which uses GNOME out of the box, works flawlessly even on fullscreen mode. But the gameplay isn't as smooth on Manjaro, benchmarking shows it only achieves average FPS of 330 (it was 400 FPS on Manjaro). I'll try other desktop environment on Manjaro and report back.

**Comment by bunkbail** [comment]
Ok I tried GNOME on Manjaro, works flawlessly with CSGO. KDE sucks haha.

**Comment by lacymorrow** [comment]
Nice! So glad you got it working, thanks for doing the testing for this!

**Comment by lacymorrow** [comment]
Notes: May not work on KDE, try GNOME if you experience issues.
