### ISSUE TITLE
settings menu drifts down when you open and then close it

### ISSUE THREAD

**Issue by peachy-keen** [lacymorrow/crossover#78]
https://imgur.com/a/sNcXTWc

**Comment by peachy-keen** [comment]
version 1.3.1

**Comment by lacymorrow** [comment]
Whoops, my bad! I'll fix this up in a new version shortly, thanks for reporting!

**Comment by peachy-keen** [comment]
> Whoops, my bad! I'll fix this up in a new version shortly, thanks for reporting!

how do I download the new release?

**Comment by lacymorrow** [comment]
Sorry for the delay, just published a new release https://github.com/lacymorrow/crossover/releases/latest
