### ISSUE TITLE
Bannable? (no)

### ISSUE THREAD

**Issue by lacymorrow** [lacymorrow/crossover#79]
CrossOver may be against the terms of service for your game, however as of this writing there has never been a ban issued in _any_ game for using CrossOver.

This app runs on Electron and does not hook into any running game code. It is still possible to be detected by low-level anti-cheat systems but so far CrossOver is not an interest to game studios.

In essence this app just displays an image on your screen. There are many other apps that can do that, as well as external devices and monitors, or even a piece of tape on the screen. There is no way to stop folks from adding a crosshair to their screen, so apps like this are allowed to live undisturbed.

That said, do not use CrossOver to cheat in competitive play. At the very least it's unethical, if not outright illegal.

**Comment by lacymorrow** [comment]
There have been reports of users not being able to load Escape from Tarkov with CrossOver running. Quitting CrossOver and restarting the game works.

This will likely be the first of a few games that lock out this app.
https://github.com/lacymorrow/crossover/issues/47#issuecomment-987762466

**Comment by t3chnoir** [comment]
Just got kicked from a raid because Tarkov detected Crossover running. The principle bothers me more than anything - what's Tarkov doing scanning apps I have on my pc that aren't interacting with Tarkov at all?

**Comment by lacymorrow** [comment]
This app is bannable in Tarkov only

**Comment by jianastrero** [comment]
Is this bannable in valorant?

**Comment by lacymorrow** [comment]
Read the comment you replied to. As of this writing:
> this app is bannable in Tarkov only

**Comment by Wuemeli** [comment]
Fortnite?

**Comment by lacymorrow** [comment]
Definitely not in Fortnite @Wuemeli, that's the game I created this for :)

**Comment by Kipiron** [comment]
Hey, could I get a confirmation if this overlay is bannable on VAC secure games? (Specifically CS2 & TF2)

**Comment by lacymorrow** [comment]
📋 Reviewed by Paperclip — categorized as discussion/community thread/wontfix. No task created.

**Comment by lacymorrow** [comment]
📋 Tracked in Paperclip as **LAC-1808**. This issue has been added to our internal project management system and will be reviewed by the engineering team.

**Comment by lacymorrow** [comment]
Tracked in Paperclip as **LAC-2589**. This issue has been added to our internal project management system and will be reviewed by the engineering team.

**Comment by lacymorrow** [comment]
Short answer: no, CrossOver is an overlay that doesn't inject into game processes. It works like a sticky note on your screen. Anti-cheat systems target memory injection, not screen overlays. Closing as answered.
