### ISSUE TITLE
CrossOver Apex Legends FullScreen

### ISSUE THREAD

**Issue by Matayosl** [lacymorrow/crossover#83]
Good Morning!.
I'm using CrossOver in Apex Legends, but in Window it's kind of bad. Is it possible for it to work on FullScreen?

Sorry My English.

**Comment by lacymorrow** [comment]
Unfortunately on of the biggest issues is that CrossOver does not play nicely with fullscreen games yet, see: https://github.com/lacymorrow/crossover/issues/1

There is a workaround, but I've heard mixed results: https://github.com/lacymorrow/crossover#hidden-by-fullscreen-apps
