### ISSUE TITLE
Mouse event hooks

### ISSUE THREAD

**Issue by lacymorrow** [lacymorrow/crossover#84]
Multiple people have requested the ability to hide or change the crosshair during ADS (right click).

I want to gauge the interest as well as understand how it would be most useful. I think the easiest would be to only implement on left/right/or middle click, but would this be sufficient?

**Comment by adeldueast** [comment]
Yeah! So WHILE holding right mousebutton for example, crosshair is hidden, and comes back when releasing right mousebutton . 

ty in advance

**Comment by lacymorrow** [comment]
Would you ever need it to be on another bind like left or middle mouse?

**Comment by lacymorrow** [comment]
Also do people ads on keyboard? Should there be a key bind for it?

**Comment by adeldueast** [comment]
Tbh ive never heard of a player who ads with anything else than right mouse button .  Left is to fire right is to aim by default in any fps game. How ever in the option , you can *if u want* change that to be anything else but like i said by default its right button to aim, left to shoot.

**Comment by lacymorrow** [comment]
This is an alpha version of the next release and includes this feature, @adeldueast if you would be willing to test and provide any feedback it would be much appreciated:
https://github.com/lacymorrow/crossover/releases/tag/2.0.0-alpha

**Comment by adeldueast** [comment]
Wow that was quick. I just tried it and I have nothing bad to say, great job !

**Comment by lacymorrow** [comment]
That's as good a review as I can ask for! I'll give it a few more days to settle and test out before I cut the actual release, thanks for contributing!
