### ISSUE TITLE
Feature request: Ability for crosshair to follow mouse cursor

### ISSUE THREAD

**Issue by snowmanstevee** [lacymorrow/crossover#87]

**Comment by lacymorrow** [comment]
@snowmanstevee:
> is there a way to make the crosshair follow your cursor?

Actually this probably is possible, I'll see about getting it into the release for this weekend maybe but most likely will be a few weeks before I get around to it.

**Comment by lacymorrow** [comment]
@snowmanstevee This is implemented in the latest release
