### ISSUE TITLE
problem with crossover

### ISSUE THREAD

**Issue by broimded** [lacymorrow/crossover#94]
so, i was playing in roblox then accidently closed crossover, i opened it again press ctrl + alt +shift + x and the cross is not moving. its stuck in one place, i tried to reinstall.

**Comment by broimded** [comment]
![image](https://user-images.githubusercontent.com/87903923/126870730-f3d256ff-ce27-44b5-b212-93001f58697a.png)

**Comment by broimded** [comment]
this is happening its just stucking

**Comment by broimded** [comment]
i placed  follow my mouse

**Comment by snowmanstevee** [comment]
I am experiencing the same problem

**Comment by broimded** [comment]
its working for me now

**Comment by snowmanstevee** [comment]
how did you get it to work?

**Comment by broimded** [comment]
i just reinstalled it and join any roblox game and started crossover. done

сб, 31 июл. 2021 г. в 22:44, snowmanstevee ***@***.***>:
