### ISSUE TITLE
Crosshair follow mouse does not work on Windows 10

### ISSUE THREAD

**Issue by snowmanstevee** [lacymorrow/crossover#95]

**Comment by lacymorrow** [comment]
This has been tested in Windows 10, are you using the latest version and is it the portable or the installed version @snowmanstevee ?

I'll have a new version in a few days that should allow me to debug easier.

**Comment by snowmanstevee** [comment]
I am using 2.1.1 the installed version

**Comment by lacymorrow** [comment]
The follow mouse behavior only turns on once you lock the crosshairs in place, by default using ‘Control+alt+shift+x’, are you locking the crosshairs? 

I’ll look at this more later today

**Comment by snowmanstevee** [comment]
Yes I am locking the crosshair but it still stays in the center of the screen when i move my cursor.

**Comment by snowmanstevee** [comment]
Update: I somehow got it following my cursor
