### ISSUE TITLE
Allow assigning keyboard keys as "hide-on-ADS" key

### ISSUE THREAD

**Issue by fullzero87** [lacymorrow/crossover#98]
I am using left ALT key for ADS.

**Comment by lacymorrow** [comment]
Yep, I had a feeling this would come up: https://github.com/lacymorrow/crossover/issues/84#issuecomment-879335813

I'll add this option in a release soon.

**Comment by adeldueast** [comment]
well, here goes the exception 😂

**Comment by fullzero87** [comment]
Also, I use xbox gamepad. It'll be nice to have ability to bind gamepad button/trigger.

**Comment by lacymorrow** [comment]
This has been added in the latest release (v2.4.0) https://github.com/lacymorrow/crossover/releases/latest
